local _, bFacts = ...

bFacts.fact = {
	"The hummingbird can have a heartbeat that measures up to 1260 beats per minute when it's in full flight",
	"Most birds do not hunt for prey and therefore do not need teeth",
	"Birds that eat insects, like worms and ants, and small animals use their beaks to grab and swallow their meal.",
	"A pair of birds can take a longer time in courtship than the very act of copulation",
	"Bird species like kiwis, ostriches, ducks, swans, and geese do not have a cloaca but have a penis instead.",
	"Birds like crows and ravens love to play.",
	"Birds act as pollinators, transferring seeds and nutrients as they fly from one region to another.",
	"The chicken is the closest living relative to the Tyrannosaurus Rex.",
	"Many birds kept as pets, including doves, parakeets, and lovebirds, enjoy living in pairs for companionship.",
	"The smallest bird egg belongs to the hummingbird and is the size of a pea.  The largest bird egg, from which the ostrich hatches, is the size of a cantaloupe.",
	"A bird's eye takes up about 50 percent of its head; our eyes take up about 5 percent of our head. To be comparable to a bird's eyes, our eyes would have to be the size of baseballs.",
	"The penguin is the only bird that can swim, but not fly. It is also the only bird that walks upright.",
	"Owls turn their heads almost 360 degrees (a complete circle) but they cannot move their eyes.",
	"Chickens have over 200 distinct noises they make for communicating.",
	"When it comes to birds, the males tend to have the more glamorous feather shape, coloration, songs, and dances.  Female birds choose their mate based on how attractive they find them!",
	"It is estimated that one third of all bird owners turn on a radio for their pet when they leave the house.",
	"The first bird domesticated by humans was the goose.",
	"Kiwi birds are blind, so they hunt by smell.",
	"Some breeds of chickens can lay colored eggs. The Ameraucana and Araucana can lay green or blue eggs.",
	"The common phrase “eat like a bird” should mean something quite different!  Many birds eat twice their weight in food each day.  In fact, a bird requires more food in proportion to its size than a baby or a cat.",
	"A group of larks is called an exaltation, a group of chickens is called a peep, a group of geese is called a gaggle, a group of ravens is called a murder, and a group of owls is called a parliament.",
	"Chickens that lay brown eggs have red ear lobes. There is a genetic link between the two.",
	"Crows have the largest cerebral hemispheres (brains), relative to body size, of any avian family.",
	"Mockingbirds can imitate many sounds, from a squeaking door to a cat meowing.",
	"Parasitic jaegers gather food by stealing it directly from the mouths of other birds.",
	"The average man would have to eat around 285 pounds of meat per day to maintain your weight if you had the metabolism of a hummingbird.",
	"Bearded vultures are the only birds to dye their plumage on purpose.",
	"The bearded vulture's diet consists of 70 to 90% bone, and it is the only bird in the world whose diet is like this, according to the World Wildlife Federation.",
	"With a wingspan of up to 9.5 feet, seen from far away, California Condors are sometimes mistaken for small aircrafts",
	"The Sword-billed Hummingbird is the only bird with a bill longer than its body.",
	"Approximately 2/3 of all the bird species are found in tropical rain forests.",
	"The longest feathers ever seen were on a chicken in Japan. Its tail feathers measured 34.7 feet (10.59 m) long.",
	"A bird's lungs are much more complicated and efficient and take up more space than those of mammals, such as humans. A human's lungs compose about 1/20 of its body, but a bird's takes up 1/5.",
	"The Australian pelican has the longest bill of any bird in the world. It is nearly 2 feet (0.5 m) in length. The sword-billed hummingbird, with its 3.9-inch (10 cm) bill, is the only bird with a bill that's longer than its body.",
	"Owls cannot swivel their eyes. Instead they move their heads completely around to see straight behind them. They live on every continent except Antarctica. Soft fringes on their wings make their flight essentially silent.",
	"In the continental U.S. alone, between 1.4 billion and 3.7 billion birds are killed by cats annually.",
	"The only bird with nostrils at the end of its beak is the kiwi. This placement helps it sniff for food, such as worms and insects on the ground. It often snorts to clear its nostrils.",
	"Unlike most birds that sing, a woodpecker will drum its beak against a tree. Other woodpeckers can identify which bird it is by the sound of the drumming.",
	"The most talkative bird in the world is the African gray parrot. One parrot could say over 800 words. Most species of parrots can learn only 50.",
	"Many birds, such as starlings, sing notes too high for humans to hear.",
	"The chicks of large bird species often take the longest to hatch. Emu chicks, for example, take 60 days to hatch. Small songbirds take just 2 weeks.",
	"A green woodpecker can eat as many as 2,000 ants per day.",
	"The Japanese crested ibis is one of the rarest birds in the world. Probably fewer than 50 crested ibises are alive today.",
	"The 1989 Exxon Valdez oil spill in Alaska polluted approximately 1,180 miles of coastline and killed up to 100,000 seabirds.",
	"The bird with the most feathers is the whistling swan, with up to 25,000 feathers. Hummingbirds, on the other hand, are so small that they have fewer than 1,000.",
	"Falconry was developed more than 4,000 years ago in eastern and central Asia. Birds were used because they could kill animals beyond the range of a hunter's weapon. Genghis Khan reportedly had 10,000 falconers.",
	"Coalminers often used canaries to detect poisonous levels of carbon monoxide gas. Miners knew that if the canary passed out, they were in danger, too. The phrase “Canary in a Coalmine” derives from this history.",
	"The marsh warbler can mimic more than 80 different birds. Other renowned mimics include mockingbirds and lyrebirds.",
	"A pelican's pouch-like beak can hold up to 2.5 gallons of water at a time. The beak will shrink to squeeze out the water before the pelican swallows its food.",
	"A vulture named the Lammergeyer will fly with bones high in the air and then drop them onto rocks. It will then eat the smashed bones, like a circus sword swallower.",
	'The bird that lays the smallest egg in the world is the bee hummingbird. Its egg is just under 0.5" x 0.25" and weighs a mere 0.02 oz',
	"Though it looks like a bird's knee is bending backwards, what is bending backward is actually its ankle. Below its ankle is an extended foot bone, leading to the toes. A bird's real knee is usually hidden by feathers.",
	"The Malleefowl is famed for making a huge compost pile for its nest. Its eggs are incubated by the heat given off by the rotting vegetation.",
	"Social weaverbirds live in huge communal nests that look like a huge haystack spread across a treetop. Some nests can weigh a few tons, have over 400 birds living in them, and may be 100 years old.",
	"The heaviest bird of prey is the Andean condor. It can weigh up to 27 lb. (12 kg.)",
	"Many scientists believe that birds evolved from dinosaurs during the Mesozoic Era about 150 million years ago.",
	"Flamingos pair for a lifetime. Some stay with their mates for 50 years or more.",
	"In the United States alone, there are over 40 million pet birds.",
	"A bird's feathers weigh more than its skeleton.",
	"The type of diet a bird eats in the wild is directly related to the shape of a bird's beak.",
	"Approximately 75% of wild birds live for less than a year. The larger the bird, the more likely it is to live longer. The large wandering albatross, for example, can live for up to 80 years.",
	"Gentoo Penguins are the fastest swimming birds, reaching speeds of 22 mph (36 kph). Emperor Penguins can stay under water for up to 18 minutes.",
	"Arctic terns have the longest annual migration of any bird. They fly 25,000 miles (40,000 m) from the Arctic to the Antarctic and then back again.",
	"The bird with the greatest wingspan of any other bird is the Wandering Albatross at up to 11.8 ft (3.63 m).",
	"The largest, tallest, and heaviest bird in the world is the ostrich. Male ostriches can reach up to 9 ft. tall (2.7 m) and weigh up to 350 lb. (160 kg). Their eyes are bigger than any other land animals' eyes and are even larger than their brain.",
	"The song of a European wren is made of more than 700 different notes a minute and can be heard 1,650 feet (500 m) away.",
	"The ostrich is the only bird that willingly takes care of other females' eggs.",
	"Ostriches do not bury their heads in the sand when danger is near. But they have been seen to lie on the ground with their long neck stretched out flat if they want to hide.",
	"The Emperor Penguin is the only bird that lays its eggs in the middle of winter. By laying its eggs so early, it gives its young a head start. The babies need all spring, summer, and fall to grow big enough to survive the next winter.",
	"Oilbirds eat oil palm fruits, which make the birds oily too. People near the caves where the oilbirds lived used to trap the oilbirds and boil them down for the oil.",
	"The fastest flying bird in a dive is the Peregrine Falcon. It averages speeds of over 110 mph (180 kph).",
	"Oilbirds are the only birds that use echolocation the way that bats do. However, bats are much better at it. A bat can even fly through the blades of a moving fan. Oilbirds are also the only nocturnal fruit-eating birds in the world.",
	"Birds have three fingers on each wing. The first, the thumb, supports a small part of the wing called the alula (a.k.a bastard wing). The second and third fingers support the main flight feathers.",
	"Birds don't fall off of a branch when they sleep because their toes automatically clench around the twig they are standing on. Because the grabbing action is done by tendons rather than muscles, the birds can sleep without danger of falling.",
	"The wishbone (or “merrythought” bone) is a bird's fused collarbone. The strongest fliers have the widest angles in their wishbones. They are the only vertebrate animals to have a fused collarbone.",
	"Not all birds have equally hollow bones. Those that dive into water—like gannets, terns, and kingfishers—and those that fly very fast, like swifts, have less air in their long bones than other birds.",
	'The word "parakeet" literally means "long tail."',
	"An albatross can soar for as long as six hours without moving its wings.",
	"Birds typically have two, three, or four toes. A typical perching bird has three pointing forward, and one back. Birds that run on hard ground have only three, all pointing forward. Ostriches only have two toes, which are shaped like an antelope hoof.",
	"A Ruby-throated Hummingbird, which weighs less than 0.2 oz., has to beat its wings more than 52 times a second to hover in front of a flower.",
	"What keeps a bird up in the air is the shape of its wings. The first humans to discover how birds stay aloft were Australian Aborigines when they invented the boomerang.",
	"The fastest level flight by a bird has been seen in both the Spine-tailed Swift and the Red-breasted Merganser (a duck). They have flown at 100 mph (161 kph) in level flight.",
	"The slowest flying bird is the American Woodcock. It can fly at just 5 mph (8 kph). When hummingbirds hover, they move at 0 mph. Additionally, hummingbirds are the only birds that can fly backwards under power, registering a negative speed.",
	"The Rufous hummingbird is the smallest migrant bird. It is less than 4 in. (9 cm) long and flies every year from Alaska to Mexico, a round trip of 3,800 miles (6,400 km).",
	"Lighthouses are dangerous for birds. The beams attract birds, especially in misty conditions, and many are killed when they fly into the glass.",
	"Birds sense winter is coming by 1) changes in hormones that cause them to put on fat, 2) the changing length of the day, and 3) sensing small changes in air pressure, which is important in predicting weather changes.",
	"Crows can recognize and remember human faces, particularly faces they associate with bad experiences. They can even share their grudge against a specific person with other crows.",
	"A group of crows is called a murder or congress. A group of owls is called a parliament, wisdom, or study. A group of flamingos is called a flamboyance.",
	"The Bald Eagle builds the largest tree nest of all birds, measuring about 9.5 ft. (2.9 m) across. The largest nest ever found was nearly 10 ft. wide and weighed close to 3 tons.",
	"Woodcocks and many ducks have their eyes placed at the sides of their heads so that they have a 360-degree field of vision.",
	"A special arrangement of blood vessels cools the blood going out to the feet and warms the blood coming back, so even when standing on the ice, birds don't lose too much heat.",
	'Both the Bee and the Vervain Hummingbirds build the smallest nests of all birds, measuring 3/4" across and 1.2" deep.',
	"The most dangerous bird in the world is the Cassowary. With one kick it can kill its enemy.",
	"Birds that are raised for meat and eggs (poultry) are the largest source of protein eaten by humans.",
	"To attract a mate, a male Frigate bird will blow up its red throat pouch. The pouch can be as big as a person's head.",
	"Depending on the species, a woodpecker's tongue can be up to 4\" long. It stores this long tongue by curling it in and sticking it through a specialized opening at the back of its neck, where it can then put it between the skull and skin.",
	"The seagulls in the Alfred Hitchcock movie The Birds (1963) were fed a mixture of wheat and whisky so they would stand around and not fly too much.",
	"The game Angry Birds has sold more than 7 million copies on Apple's iPhone. The game was made by a team of just four people. It was such a low priority for the company that it took over 8 months to finish.",
	"Wind farms kill approximately a half-million birds per year in the United States, according to a 2008 Fish and Wildlife study.",
	"Approximately 200 people have died since 1988 because of airborne collision between airplanes and birds.",
	"The first recorded bird strike was in 1905, when Orville Wright's plane hit a bird and killed it.",
	"In the novel To Kill a Mockingbird (1960), author Harper Lee used the mockingbird to symbolize innocence.",
	'The smallest flightless bird is the Island Rail. This tiny bird lives on the remote island of Tristan da Cunha in the Atlantic Ocean and is just 5" long, about the same size as a hen chick.',
	"The earliest known bird is the Archaeopteryx. It lived during the Jurassic period 150 million years ago. Because it did not have the basic features of flight, scientists are uncertain if it could fly",
	"Vultures have stomach acid so corrosive that they can digest carcasses infected with anthrax.",
	"No other living being other than birds have feathers. The main function is to help them fly. They also waterproof birds and protect them from UV rays and other harmful elements.",
	"A Bald Eagle is called “bald” because it is piebald (black and white), not because it doesn't have any feathers.",
	"Eleven percent of the world's bird species is endangered. Draining wetlands and felling forests are the main causes of damage, but pollution and pesticides also play a part.",
	"Before 1840, there were thousands of millions of passenger pigeons in North America. However, they were slaughtered for food until only one was left, a female called Martha. She died when she was 12 years old in 1914, in a zoo in Ohio.",
	'The word "swan" is derived from the Indo-European root *swen, meaning "to sound, to sing."',
	'Someone who suffers from "anatidaephobia" believes that somewhere, somehow a duck or goose is constantly watching them.',
	"There are more fake flamingos on Earth than real ones.",
	"Though the term “eagle eyed” implies that eagles have keen vision, only the Wedge-tailed Eagle can see better than humans (2.5 times better). Kestrels and falcons have about the same power of sight as we do.",
	'The word "falcon" is from the Latin "falx," meaning "curved blade, pruning hook, sickle, war-scythe."',
	'A flock of ravens is called an “unkindness” or a "conspiracy."',
	"Esmeraldas Woodstar is one of the world's rarest and smallest hummingbirds, measuring barely 2½ inches long. It was thought to be extinct until it was rediscovered in 1990 after not being sighted since 1912.",
	"About two-thirds of birds in North America are at risk of extinction due to climate change.",
	"Unlike most animals, rather than producing liquid urine, birds create a white, pasty substance",
	"Ostriches are different than all the other bird species in that they do have a complete separation of feces and urine, but they still don't have a bladder like most mammals.",
	"A bird's lungs take up much more space in their bodies than a human's does. For example, a human's lungs makes up one twentieth of their body while a bird's take up one fifth",
	"Alabama's state bird is the Yellowhammer (also known as Northern Flicker)",
	--[['Alaska\'s state bird is the Willow Ptarmigan',
        'Arizona\'s state bird is the Cactus Wren',
        'Arkansas\'s state bird is the Mockingbird',
        'California\'s state bird is the California Quail',
        'Colorado\'s state bird is the Lark Bunting',
        'Connecticut\'s state bird is the American Robin',
        'Delaware\'s state bird is the Blue Hen Chicken',
        'Florida\'s state bird is the Mockingbird',
        'Georgia\'s state bird is the Brown Thrasher',
        'Hawaii\'s state bird is the Nene (Hawaiian Goose)',
        'Idaho\'s state bird is the Mountain Bluebird',
        'Illinois\'s state bird is the Cardinal',
        'Indiana\'s state bird is the Cardinal',
        'Iowa\'s state bird is the Eastern Goldfinch',
        'Kansas\'s state bird is the Western Meadowlark',
        'Kentucky\'s state bird is the Kentucky Warbler',
        'Louisiana\'s state bird is the Eastern Brown Pelican',
        'Maine\'s state bird is the Black-capped Chickadee',
        'Maryland\'s state bird is the Baltimore Oriole',
        'Massachusetts\'s state bird is the Black-capped Chickadee',
        'Michigan\'s state bird is the American Robin',
        'Minnesota\'s state bird is the Common Loon',
        'Mississippi\'s state bird is the Mockingbird',
        'Missouri\'s state bird is the Eastern Bluebird',
        'Montana\'s state bird is the Western Meadowlark',
        'Nebraska\'s state bird is the Western Meadowlark',
        'Nevada\'s state bird is the Mountain Bluebird',
        'New Hampshire\'s state bird is the Purple Finch',
        'New Jersey\'s state bird is the Eastern Goldfinch',
        'New Mexico\'s state bird is the Roadrunner',
        'New York\'s state bird is the Eastern Bluebird',
        'North Carolina\'s state bird is the Cardinal',
        'North Dakota\'s state bird is the Western Meadowlark',
        'Ohio\'s state bird is the Cardinal',
        'Oklahoma\'s state bird is the Scissor-tailed Flycatcher',
        'Oregon\'s state bird is the Western Meadowlark',
        'Pennsylvania\'s state bird is the Ruffed Grouse',
        'Rhode Island\'s state bird is the Rhode Island Red',
        'South Carolina\'s state bird is the Carolina Wren',
        'South Dakota\'s state bird is the Ring-necked Pheasant',
        'Tennessee\'s state bird is the Mockingbird',
        'Texas\'s state bird is the Mockingbird',
        'Utah\'s state bird is the California Gull',
        'Vermont\'s state bird is the Hermit Thrush',
        'Virginia\'s state bird is the Cardinal',
        'Washington\'s state bird is the Willow Goldfinch',
        'West Virginia\'s state bird is the Cardinal',
        'Wisconsin\'s state bird is the American Robin',
        'Wyoming\'s state bird is the Western Meadowlark',]]
	--
	"Contrary to their portrayal in cartoons, roadrunners are not nearly as fast as coyotes. That said, they're pretty fast for birds. The land speed of a roadrunner is typically around 15 mph, though the bird can move faster in short bursts.",
	"There are 2 types of roadrunners: Greater (2ft, black/brown/white feathers, shaggy crest) & Lesser (smaller, lighter tan). Both have long tail feathers for balance.",
	"Roadrunners are omnivores that eat ground prey, including rattlesnakes. They primarily consume scorpions, frogs, reptiles, small mammals, birds, and eggs. If a pair wants to eat a rattlesnake, they work together to peck its head until it dies.",
	'Roadrunners are fast birds of the cuckoo family. The greater roadrunner\'s Latin name "Geococcyx californianus" means Californian earth-cuckoo.',
	"Roadrunners are charismatic birds, and being fleet of foot might just make them feel confident about exploring whatever they're curious about—including people.",
	"On cool desert nights, roadrunners allow their body temperature to drop to conserve their energy. To recover from their cold night, roadrunners spend the morning lying out in the sun, with their feathers raised to allow the sun to reach their skin.",
	"A group of geese is called a 'gaggle'. However, when they are in the sky they are they are a 'skein'",
	"A group of vultures on the ground or perched in trees is called a 'venue.' If they are circling on thermals of hot air, however, they are referred to as a \"kettle\".",
	"Many owl species are solitary, coming together only during breeding seasons. On the occasions when owls are seen together, the group is called a “parliament.”",
	"A group of peacocks is called an “ostentation.” Since ostentation means a pretentious or conspicuous show or display, it is easy to see why this name may fit the showy peacocks.",
	"Birds of a feather flock together",
	"Sparrows put the stubs of cigarettes in the lining of their nests. The reason they do this is to deter mites",
	"The beak of the great tit cleverly changes shape (very slightly) over the year to help it adapt to changes in its food supply from insects to nuts and seeds.",
	"Starlings are superb mimics. They can copy the sounds of other birds, and even frogs!",
	"House martins migrate all the way to Africa in winter, and then fly back to Britain and set up home in exactly the same nest.",
	"Starlings come together at night to roost in enormous numbers. The largest roosts can contain a million birds!",
	"Swifts gather flying insects into huge food balls, which contain between 300 and 1,000 insects each. The birds then use them to feed their young.",
	"You can tell male and female starlings apart by the colour of the base of the bill - blue for males, pink for females.",
	"Back when milk was delivered in glass bottles in Britain, the Blue Tit bird used to pierce the foil lid and drink the cream. This largely stopped when semi-skimmed milk became popular.",
	"Robins are incredibly charitable birds, sometimes feeding the chicks of other species - they just can't resist helping a hungry baby bird!",
	"Collared Doves are not master nest-makers - sometimes their chicks fall through the flimsy branches.",
	"Blackbirds love to sunbathe! They sit on the ground and spread out their wings to catch the rays.",
	"Birds have an incredibly high body temperature of 40°C, which requires a lot of energy to maintain. Birds have to eat enough during the day to keep them alive overnight - if not, they die before dawn.",
	"Blue tit birds are so light, they weigh about the same as a pound coin.",
	"Great Spotted Woodpeckers make their distinctive knocking sound by striking a branch with their bills an incredible 40 times a second.",
	"Wrens spend cold winters huddling together in nests for warmth. An astonishing 63 wrens were once found huddled in one nest box.",
	"Swallows can cover enormous distances during daylight migration - up to 200 miles a day.",
	"The jay bird stashes away about 5000 acorns every season in different hiding places. It can remember all the locations, but often it doesn't need to eat all the acorns, leaving them to grow into oak trees.",
	"Robins love singing so much, they do it all year round. They are normally the first to start the dawn chorus, and the last ones to stop at night.",
	"During winter, blackbird couples split up, but as soon as breeding season arrives, the pair up again, often with the same partner as before. Aw!",
	"Coal tit birds often purposefully lost battles of superiority over food, so they can hide it for later. They build a winter store of peanuts and sunflower seeds.",
	"Dunnock birds have one main partner for life, but they also have many other mates on the side. Females are just as likely to have affairs as males.",
	"During late summer and autumn, birds moult. Blackbirds are very embarrassed by this, and hide themselves away until their new feathers grow, leading people to think that the birds have disappeared.",
	"British robins are not afraid of humans, often coming quite close when we're gardening in the hope that we'll turn over the soil and expose tasty grub for them. European robins are not so brave.",
	"The tit family of birds spend most of their lives looking for something to eat. The great tit spends around 75% of its time searching for food. For the blue tit, it's more like 80%, and for the coal tit it can be 90%!",
	"The tits, chickadees, and titmice constitute the Paridae, a large family of small passerine birds which occur mainly in the Northern Hemisphere and Africa. Most were formerly classified in the genus Parus. ",
	"To draw a predator away from its nest, a Killdeer bird will drag its wing across the ground, faking an injury. When their display leads the threat away from the nest, they will suddenly become flightworthy and take off",
	"Some male birds, such as male Northern Cardinals, are known to fight their own reflections in a window, vehicle mirror, or chrome hubcap. It is believe these males believe their reflection is a competing bird and attack it",
	"Some birds deliberately disturb an ant mound and allow the ants to crawl over them. They smash the ants to get their ant juices on their feathers. It's believed the ant juices help eliminate parasites in their feathers",
	"Vultures like to urinate and defecate on their legs in order to stay cool via evaporative cooling. This is called urohidrosis",
	"Flycatchers and other birds that mainly hunt bugs will hunt flying insects in a technique called hawking. They simply perch on a branch and quickly dart out to snap the bug out of the air.",
	"Some gulls will carry clams or oysters high above the group and drop them onto rocks to break open the shells",
	"Crows use twigs to fish insects out of cracks and crevices",
	"Most predatory birds have strong feet and long, sharp talons to grasp and kill prey. Shrikes are predatory songbirds that lack this equipment but are still successful at hunting small birds and rodents",
	"Loggerhead and Northern Shrikes are predatory birds but don't have sharp talons to hunt their prey. They use their hooked beaks to impale their prey on barbed wire and rip them into bite size pieces! That's metal!",
	"All birds preen their feathers with their bills to keep them in good condition. Some birds, like the Great Blue Herons, have a middle claw with a serrated edge that acts like a comb. This class is called a pectinate claw.",
	"Nearly all birds will, at times, draw one leg up into their belly feathers for warmth and remain standing on the other leg.",
	"The Frillback is a breed of pigeon developed over many years of selective breeding. Frillbacks, along with other varieties of domesticated pigeons, are all descendants from the rock pigeon (Columba livia)",
	"The Frillback pigeon is a common and very popular breed of the domesticated pigeons. It is known for the frill or curls on the wing shield feathers.",
	"The quality of a Frillback bird is based on a 100-point scale, with the head constituting 15 points, the color constituting 15 points, the body constituting 10 points, the curl constituting 50 points, and the muff constituting 10 points.",
	"The Frillback pigeon is an exhibition or show breed. It is good for ornamental purpose and also good for raising as pets as they have a calm temperament.",
	"In daylight, birds crash into windows because they see reflections of vegetation or see through the glass to potted plants or vegetation on the other side. At night, nocturnal migrants (most songbirds) crash because they fly into lighted windows.",
	"Female toucans typically have higher voices than males. They use their calls to rally other birds to good foraging sites and to differentiate themselves from other groups of toucans.",
	"Falcons devote themselves to one partner for their reproductive years. However, this doesn't mean they act like a married couple. Falcons only come together to mate, and otherwise spend their lives as solitary hunters.",
	"Great Horned Owls, like other owls, are clueless about building nests. They use other available structures to nest in, which include stick nests of hawks and crows, squirrel nests, and a variety of artificial nests put up by humans.",
	"Contrary to popular belief, most birds are NOT government drones. However, this topic is heavily debated.",
	"Some bird species, such as the Common Loon, almost always have their feet in the water. Sometimes they'll lift their legs out of the water, shake off excess water, and tuck it under their wing for warmth.",
	"Chicken-like birds, such as the Sage Grouse, perform some of the more elaborate courtship displays in the bird world. Males gather in an open area to dance and strut and sometimes fight for the admiring females.",
	"Some birds not only lay eggs in their own nests, but they also lay some in the nests of other females in their species. Wood Ducks and Common Goldeneyes will even lay some of their eggs in the nests of other species!",
	"The Osprey bird is a fish-eating raptor with special feet. They have small, spine tipped projections, called papillae, on the bottom of their feet that help them hold their slippery fish prey",
	"Red-headed Woodpeckers experience the highest g-forces of all woodpeckers. When pecking wood, they hit trees up to 20 times per second about 12,000 times for day. Their brains experience 1000g's of deceleration!",
	"Owls cannot twist their heads all the way around, as some people think. With 14 vertebrae in their necks, owls can turn their heads up to 280 degrees!",
	"Bird claws are well adapted for daily activities. Birds that climb tree trunks, for example, have claws that are more curved compared with those of non-climbing species.",
	"The thermoregulation system of birds is very different from that of mammals. In mammals, the digestion of food produces heat and keeps their temperature around 98°F. Birds, however, need to shiver their muscles to maintain 106°F.",
	"Birds have large deposits of white fat in their bodies, mostly concentrated in the chest. White fat fuels flight and provides birds with the energy they need to shiver their muscles to keep warm.",
	"The Eurasian swift can stay in the air for months before they get sexually mature. They drink water by flying close to the surface of lakes and sleep flying high up in circles with one eye open. They land when sexually mature to raise young.",
	"Some birds that migrate from Europe to west Africa fly over the Sahara in one go without stopping to drink or eat. Climate change makes the journey even harder as the Sahara is expanding.",
	"Some hummingbirds have heart rates from 400-1200 bpm, but during their resting cycle (called Torpor), their heart rates can dip as low as 40 bpm.",
	"During mating displays, some male hummingbirds can pull up to 9 Gs.",
	"Turkey vultures are thought to have the strongest sense of smell of any vulture. In fact, their sense of smell is so strong that they are used as an indicator by gas companies to find gas leaks.",
	"Birds were the first animal found to be capable of keeping a musical beat, even when the tempo changes. The second animal found to have this capability was the Sea Lion.",
	"Birds ears are slightly offset. This gives them stereoscopic hearing capabilities. When a songbird calls, the birds can hear each individual frequency and tril. They get data about the amplitude, frequency, duration, direction of the sound waves.",
	"Baby birds will babble and go through baby talk as they learn to sing. Their throat structure does not have vocal cords but instead their entire throat is a resonating trumpet-like tube called the syrinx.",
	"Turkey Vultures produce antibodies to make them immune from botulism so they can eat rotting food that would harm other animals if they ate it.",
	"Birds breathe continuously - both in and out at the same time, constantly. It’s how they can manage to fly long distances, delivering a steady stream of oxygen throughout their bodies without breaks.",
	"Nuthatches are the only UK bird that can climb headfirst down tree trunks.",
	"House Finches are a common bird in much of the United States nowadays. They were originally only a resident of the Desert Southwest and Mexico. In the 1940’s someone brought them illegally to the East Coast and the birds were ultimately released.",
	"Zebra finches can metabolise their body fat and convert it to water to stay hydrated. They also have a specific song that they sing to eggs during droughts that causes the young to incubate for longer and hatch smaller and leaner to survive.",
	"Cockatoos have a dominant and non dominant foot. Most black cockatoos are left foot dominant ie they perch on their right and eat with their left foot.",
	"Baby emus have adorable striped camouflage and an instinct to tumble and roll at random intervals to avoid aerial predators.",
	"A lot of large parrots (macaws, cockatoos, African greys, etc) can live between 50-60yrs on average! One of the oldest known birds(a blue and yellow macaw) is about 124 and named Charlie.",
	"When a Peregrine Falcon pulls out of a full stoop (dive; that could reach 240+ mph) it has been estimated that they withstand over 27 Gs.",
	"The Hooded Pitohui is one of several known poisonous birds.",
	"Humans have more in common with birds than we do with all other primates regarding communication, particularly how we learn to communicate by way of mimicking.",
	"The entire starling population in North America started from 100 birds released in 1890. This wasn’t the first time introduction was attempted but the first time the birds survived. The current population in North America is over 150 million.",
	"Birds have special blood circulatory systems that help keep their feet from freezing called Rete mirabile- 'wonderful net' in Latin. It cools blood going into the feet to minimize heat loss, then warms it back up as it returns to the heart.",
	"North America used to be home to 5 to 10 billion passenger pigeons, which at the time were the most numerous birds on earth. One estimate put the size of a single flock at 2 billion birds.",
	"Lots of waterfowl like loons and grebes cannot take off from dry ground or walk on solid land because their legs are structured for swift swimming and can’t support the amount of body weight without the added buoyancy of water.",
	"Most raptor birds leave the nest at their full adult size after only about 12 weeks and are then eventually chased off the territory by their parents, who view them as competition for food.",
	"You can get a rough estimate of how old a raptor bird is by their plumage (juvenile plumage will molt out at about one year of age) and their eye color. Light eyes = young bird.",
	"Ayam Cemani is a rare breed of chicken from Indonesia. They have a dominant gene that causes hyperpigmentation (fibromelanosis), making the chicken mostly black, including feathers, beak, and internal organs.",
	"Kakapo birds are herbivores with a diverse diet including seeds, fruits, pollen, and plant material. They have a unique digestive system that allows them to extract maximum nutrients from fibrous plants.",
	"Kakapo birds are nocturnal and solitary, spending their days hidden in vegetation. They are excellent climbers, using their strong legs and beaks to move through trees.",
	"Kakapos have an unusual breeding system called lek breeding. Males gather in specific areas and compete for female attention through elaborate displays and booming calls. This typically occurs every 2-4 years when rimu trees produce abundant fruit.",
	"Kakapos birds are endemic to New Zealand, historically found throughout the country's forests. Today, they are restricted to predator-free island sanctuaries, primarily Codfish Island (Whenua Hou) and Little Barrier Island (Hauturu-o-Toi).",
	"The Chinstrap Penguin is easily identifiable by its distinctive black band extending from ear to ear under its chin, resembling a helmet strap. Its back and flippers are black, contrasting sharply with its white underparts and face.",
	"Chinstrap Penguins primarily feed on krill, which accounts for about 95% of their diet. They also consume small fish and squid. These penguins are skilled divers, capable of reaching depths of 70 meters to forage for food.",
	"Chinstrap Penguins are highly social, often forming large colonies during breeding season. They are agile swimmers, using their flippers to 'fly' underwater at speeds up to 30 km/h (8.3 mph).",
	"Chinstrap Penguins are known for their loud, harsh calls. During the breeding season, they produce a variety of vocalisations, including a high-pitched, repetitive screech often described as an 'ecstatic display call'.",
	"Chinstrap Penguins inhabit the Antarctic Peninsula, South Shetland, South Orkney, and South Sandwich Islands. They prefer rocky, ice-free areas for nesting, often on steep slopes or cliffs near the shore.",
	"The Cinereous Vulture is a massive bird of prey characterised by its dark brown to black plumage, which gives it a sombre, monk-like appearance. Unlike other vultures, its head is covered in fine, dark feathers, and it has a distinctive hooked beak.",
}

bFacts.wow = {
	"Many species of birds can be found on the worlds of Azeroth, Outland and Draenor. They mostly fall under the categories of carrion birds and birds of prey. Many other kinds of birds exist as pets and critters like turkeys and parrots.",
	"Among the Explorers' League, there are those who believe that birds are descended from dinosaurs such as an extinct type of raptor that had feathered arms. The feathers suggest some kind of missing link between the two different kinds of animals.",
	"Albatrosses are large, coastal-dwelling birds similar to seagulls. Many sailors believe that harming an albatross will bring terrible luck upon their voyage.",
	"Albatross Chicks can be captured in pet battles in Azsuna and Stormheim.",
	"Great Sea Albatross (pet) can be captured in pet battles in Nazjatar.",
	"Siltwing Albatross can be purchased from vendors for 1000 Seafarer's Dubloons.",
	"Highwind Albatrosses are found flying all over the Timeless Isle. They drop no loot, but instead have the unique ability to grab the player who attacks it and then ending combat and resuming its patrol, ferrying the player all around the island.",
	"Highwind Albatrosses fly in a counterclockwise loop of the Timeless Isle, but turn inland after flying past Huojin Landing, crossing over the Mossgreen Lake and circling around Red Stone Run before flying back westward over the Celestial Court.",
	"Agitated Albatrosses are albatrosses located in Crosswind Commons in Boralus. They are only visible during the world quest Albatrocity.",
	"Brinebeak Albatrosses are albatrosses located in Stormsong Valley and on Mechagon Island.",
	"Great Sea Albatrosses are albatrosses located in Nazmir.",
	"South Sea Albatrosses are albatrosses located in Zuldazar.",
	"Vicious Albatrosses are albatrosses that spawn during the Beachhead world quest to attack Juvenile Turtles.",
	"Axebeaks are birds native to Draenor and Azeroth. They can mainly be found in Tanaan Jungle, the jungle areas of Gorgrond, and some parts of the Waking Shores. They appear to be omnivorous, as some can be seen eating corpses and others eating fruit.",
	"The edges of Axebeaks' beaks are particularly sharp. The ancient tribes of Draenor were known to harvest the bloodbeaks' sharp beaks for crude tools and weapons.",
	"Blighted Axebeaks are axebeaks located in Everbloom Wilds in Gorgrond.",
	"Bloodthirsty Axebeaks are axebeaks located in Tanaan Jungle during the Assault on the Dark Portal. They have two abilities: Dive and Putrid Dive.",
	"Greater Axebeaks are axebeaks located in Tanaan Jungle. They have one ability, Peck, which deals Physical damage.",
	"Jungle Axebeaks are axebeaks located in Gorgrond. They have one ability, Peck, which deals Physical damage.",
	"Wandering Axebeaks are axebeaks located in Zuldazar and Dazar'alor. They have two abilities, Peck and Talon Rake, which both deal Physical damage. They also come in a violet-feathered variant.",
	"Axebeaks are obviously based on real-world toucans. Their axe-shaped beaks might have been inspired by the dodo creature concept.",
	"[Mechanical Axebeak] can be crafted by Engineers.",
	"[Fruit Hunter] hatches from the Wiggling Egg treasure in Grom'gar after 3 days.",
	"Junglebeaks and Axebeak Hatchlings can both be captured in pet battles in Gorgrond.",
	"Bloodbeaks can be captured in pet battles in Tanaan Jungle.",
	"Bush chickens are a species of small, flightless birds, found on Azeroth. Following their introduction to the mainland by the goblins, they have become the entrée-du-jour for Pilgrim's Bounty due to their high deliciousness and low intelligence.",
	"[Frightened Bush Chicken] has a chance to drop from  [Pilgrim's Bounty].",
	"Vultures are carrion birds that can be found throughout the drier areas of Kalimdor — seeking carnage upon which to feed. The mottled scavengers have been known to aid the vile harpies — drawn by the promise of freshly slain flesh and blood.",
	"Boulderfist clan legend recounts a cloud of carrion birds following ogre warriors through the Dark Portal during the Second War; it may be that all two-headed scavengers in Azeroth are their descendants.",
	"Angered Arakkoa Protectors are two-headed ghost vultures summoned by several arakkoas in Blade's Edge Mountains.",
	"Barrens Vultures can be found in the Northern Barrens.",
	"Bonelashers are vultures found in the Bone Wastes of Terokkar Forest.",
	"Bonestripper Buzzards are two-headed vultures found in the Hellfire Peninsula.",
	"Buzzards are a species of scavengers bird like vultures. Critter buzzards are neutral critters can be found in the Tanaris.",
	"Carrion Birds are vultures found in Uldum.",
	"Carrion Vultures are vultures located in Townlong Steppes.",
	"Darktail Bonepickers are vultures found in the Blasted Lands.",
	"Defiant Swoops are vultures found in Desolace.",
	"Fledgling Buzzards are vultures located in Redridge Mountains.",
	"Fleshrippers, Young Fleshrippers and Greater Fleshrippers vultures are found in Westfall.",
	"Giant Buzzards are found in the Badlands, and due to living in a desert, can often be found parched or starving.",
	"Loch Buzzards are vultures found in Loch Modan.",
	"Mesa Buzzards are found in the Arathi Highlands, also appearing in the elder and young variations.",
	"Sky Shadows vultures can be found in the Deadwind Pass.",
	"Summit Bonestripper vultures can be found in Kun-Lai Summit.",
	"Swoops, Wiry Swoops and Taloned Swoops are vultures found in Mulgore.",
	"Thrashtalon Vultures can be found in Gorgrond.",
	"Twilight Buzzards can be found in Mount Hyjal.",
	"Due to the Cataclysm, the Carrion Vultures of the Western Plaguelands have gone extinct.",
	"Salt Flats Vultures were wiped out during the Cataclysm. Their corpses can still be found floating in Thousand Needles. The scavenger variation has also gone extinct, but their corpses aren't found in-game.",
	"Due to the Cataclysm, the Mountain Buzzard variation in Loch Modan is now extinct.",
	"Due to the Cataclysm, the Wayward Buzzard variation in Tanaris is now extinct.",
	"Bonechewer is a rare ghostly vulture on the top of a Scarlet Palisade's tower in Tirisfal Glades.",
	"Catal and Favored of Isiset are rare two-headed vultures found in Burning Steppes.",
	"Fene-mal is a rare two-headed vulture, who can be found in the Eastern Plaguelands.",
	"Heress is a rare two-headed vulture found in the Western Plaguelands.",
	"Ripwing is a rare mob found in Arathi Highlands.",
	"Spiteflayer is a rare vulture, who can be found in the Blasted Lands. He has a two-headed model, so he presumably comes from Outland.",
	"Torgos and his mate Trachela can be found the Terokkar Forest. He is considered the king of the boneflayer vultures.",
	"Vultros is a rare vulture found in Westfall.",
	"Zaricotl is a rare vulture found in the Badlands.",
	"The [Waste Marauder] vulture mount drops from Rotfeaster in Uldum.",
	"Chickens are domesticated bird critters found in many areas of Azeroth. They tend to avoid crossing roads, regardless of motivations.",
	"Clucks is an untameable, Common level 3 chicken battle pet. It is one of the battle pets of Old MacDonald in Westfall, along with Foe Reaper 800 and Teensy.",
	"El Pollo Grande, the Black Chicken of Death, is a huge black chicken accidentally summoned by Niby the Almighty in Felwood. Niby promptly declared that Vengeance will be mine! Death to Stormwind! Death by chicken!",
	"Hillpaw's Chickens are chickens located in the Heartland in the Valley of the Four Winds. They can be revealed to be a Wild Prairie Chicken, Amorous Rooster, Lost Hen, Disguised Marmot, or[Old Hillpaw's Prize Chicken].",
	'"Plucky" Johnson is a human, who has been turned into a chicken, found at the Mirage Raceway in the Thousand Needles. He is Magus Tirth\'s polymorphed apprentice. Wanting to avoid Tirth, he turned himself into a chicken to hide from the master mage.',
	'The Cloaking Chicken was a mechanical chicken located at Skull Rock in Durotar. Here it was found cloaking Sully "The Pickle" McLeary and Amber Kearnen, who were overlooking the Dranosh\'ar Blockade.',
	"Homing Robot OOX-09/HL is a mechanical chicken quest giver located on a small islet in the lake just northeast of Agol'watha in the Hinterlands.",
	"Homing Robot OOX-17/TN is a mechanical chicken quest giver located in the mountains just east of the Gaping Chasm in Tanaris.",
	"Homing Robot OOX-22/FE is a mechanical chicken quest giver located at Feral Scar Vale in Feralas. It can be found on the ground before the second cave.",
	"Mechachicken is an oversized mechanical chicken originally part of the Town-In-A-Box package. It was designed to provide food in case of emergencies.",
	"Amorous Roosters are chickens that appear during the Chasing the Chicken quest in the Valley of the Four Winds. When searching for Old Hillpaw's prize chicken, one may catch a rooster. Should this happen, simply dunk it.",
	"Chicken Escapees are critters found out of Frenzyheart Hill in Sholazar Basin.",
	'Dun Morogh Chickens are chicken critters that wander just outside of Ironforge in Dun Morogh. One can also be found in Chelie Coldanvil\'s menagerie of "exotic" creatures at Arbor Glen in Shadowmoon Valley.',
	"Frightened Chickens are critters running loose in Merchant Square in Gilneas City.",
	"Moor Hens are chickens found at Marl's Stead and Bradensbrook in Val'sharah and Skyhorn in Highmountain.",
	"White Chickens are chicken critters found in Orgrimmar, Ruins of Gilneas, and Valley of the Four Winds.",
	"Haywire Battle-Chickens are mechanical chickens created by Bingles Blastenheimer who rebelled with jealousy when he was working on his new invention, the Skystrider. They are encountered in Ironwing Cavern while on the Bird is the Word quest.",
	'[Ancona Chicken] can be purchased from "Plucky" Johnson in Thousand Needles at a cost of 1g.',
	"Chickens can be captured in pet battles in various zones.",
	"Robo-Chicks can be captured in pet battles in Azshara, Orgrimmar and Winterspring.",
	"[Rocket Chicken] is obtained from a rare loot card in the TCG expansion March of the Legion.",
	"Szechuan Chickens can be captured in pet battles in Kun-Lai Summit.",
	"Rustbolt Clucker can be captured in pet battles in Mechagon.",
	"Valley Chicken can be captured in pet battles in Stormsong Valley.",
	"[Gnomish Battle Chicken] can be crafted by Gnome Engineers.",
	"Condors are carrion birds, found in the Redridge Mountains, Borean Tundra, and Dragonblight.",
	"Carrion Condors are found in Transborea, a region of Borean Tundra.",
	"Cypress Condors are found in The Jade Forest.",
	'Dire Condors are carrion birds found in the Redridge Mountains. They drop Condor Giblets which are used for the quest "Franks and Beans".',
	"Dragonbone Condors are found in the Dragon Wastes of Dragonblight, living on the bones of the dead dragons.",
	"Fleshbeak Scavengers are condors located near Karabor in Shadowmoon Valley.",
	"Frostbeak Scavengers, Frostfire Bonestrippers, Frostfire Fleshrippers, Juvenile Bonestrippers and Trained Bonestrippers are found in Frostfire Ridge.",
	"Kun-Lai Corpsepickers are found near Ox Gate in Kun-Lai Summit.",
	"Ridge Condors are condors located in Frostwall and in the Bones of Agurak and Iron Siegeworks in Frostfire Ridge.",
	"Thunderbirds and Trenchwing Scavengers are condors found in Krasarang Wilds.",
	"Arae is a rare condor located in the hills immediately south of Sun Rock Retreat in Stonetalon Mountains.",
	"Corpsefeeder is a rare carrion bird located near the Forsaken Front in Silverpine Forest.",
	"Dreadtalon is a condor found in the Dragon Wastes of Dragonblight. He has been attacking numerous Horde caravans traveling to and from Venomspite, and for this Captain Gort has orders from Overlord Agmar to tell players to kill him.",
	"Lord Condar is a rare condor found southwest of Farstrider Lodge in Loch Modan. He is on a 2-3 hour respawn timer.",
	'The  [Blue Mini Jouster] and  [Gold Mini Jouster] are the possible quest rewards for "Egg Wave". Both of them carry little straw puppets with toy pikes on their heads.',
	"Cranes are large birds native to Pandaria, and also found in the Shadowlands in Bastion and Ardenweald. They make their first appearance in Mists of Pandaria, and later in Shadowlands. These creatures should not be confused with tallstriders.",
	"Chi-Ji the Red Crane is one of the four creatures known as the August Celestials who watch over Pandaria.",
	"The majestic crane is a treasured friend of the pandaren.",
	"The pandaren of the Krasarang Wilds believe the cranes of Krasarang to be gifts from Chi-Ji, and their feathers are used to adorn garments and to fletch arrows.",
	"It is said that each crane flock appoints a sentry who stands guard with a stone in its beak, so that, should it fall asleep, the stone drops and it awakens.",
	"The Windfeather species of crane, found only on the Timeless Isle, are capable of producing brilliant plumage, and are highly protective of their nests.",
	"The Windfeather species of crane seem to have an affinity with the winds, and can smooth down their feathers, allowing them to rapidly strike predators.",
	"The matriarchs of the Windfeather species of cranes sing a soothing melody, calming the chicks when they are agitated. The males seem particularly fierce, and will ruffle their feathers to sweep a powerful gust of wind at attackers.",
	"The meat of the Windfeather cranes makes for a savory, if lean, meal. Their feathers seem to have the ability to lighten spirits, and may have magical properties.",
	"Crane chicks of the Timeless Isle sometimes sing a curious song that calms the nerves and soothes the soul.",
	"The feathers of the Windfeather crane are surprisingly light to the touch and will fly away with the slightest breeze.",
	"Autumn is a crane mount and animal companion of Lorewalker Cho. Unlike Summer and Mishi, Autumn is only seen in Cho's home at Dreamer's Pavilion in the Jade Forest.",
	"Chi-Ji the Red Crane is one of the four creatures known as the August Celestials who watch over Pandaria. He watches over the Valley of the Four Winds and Krasarang Wilds and is sometimes referred to as the Southern Celestial or the Spirit of Hope.",
	"The Emerald Gander is a rare crane found in the woods west of the Celestial Court on the Timeless Isle.",
	"Kracor is a crane located at the Gilded Fan in the Valley of the Four Winds.",
	"Mr. Crane or 'the Crane' is a crane befriended by Li Li Stormstout. She can summon him using a special whistle.",
	"Needlebeak <Lord of the Flock> is a crane located in the Krasarang Wilds.",
	"Patrannache is a rare elite crane found in Valley of the Four Winds. He remains invisible until a hunter uses a Flare to unveil him. He was the only pink crane found in World of Warcraft, until Brilliant Windfeathers appeared on the Timeless Isle.",
	"The Songbird Queen is a crane that can be found in the Scrollkeeper's Sanctum of the Temple of the Jade Serpent. The Songbird Queen most likely comes from the pandaren literature that been brought to life by Haunting Sha.",
	"Ancient Bloodcrown Cranes are cranes located in the Krasarang Wilds.",
	"Carp Hunters are cranes located at Krasari Ruins in the Krasarang Wilds.",
	"Children of Chi-Ji are cranes located in Krasarang Wilds. They are also summoned by Chi-Ji on Timeless Isle. They drop Pristine Golden Crownfeathers",
	"Crested Bandit Cranes are cranes located near ponds and rivers in the lower central Jade Forest.",
	"Exotic Pet Cranes are cranes found at the Dreamer's Pavilion in the Jade Forest.",
	"Glade Hunters are cranes located in the Gilded Fan in the Valley of the Four Winds. Several of them were killed by Manglemaw.",
	"Glade Singers are cranes located at the Gilded Fan in the Valley of the Four Winds, known for singing their songs, putting their enemies to sleep for 3 seconds.",
	'Glade Sprinters are cranes located in the Gilded Fan in the Valley of the Four Winds. They drop Spindly Bloodfeathers for the quest "Watery Woes".',
	'Great Cranes are cranes located at Narsong Spires in the Krasarang Wilds. They are the objective of the quest "Who Knew Fish Liked Eggs?"',
	"Ink-Tipped Cranes are cranes found at the Jade Temple Grounds and the Arboretum in the Jade Forest.",
	"Lotus Cranes are cranes located in Shang's Valley in the Jade Forest.",
	"Lushwater Cranes are cranes located in A Little Patience.",
	"Sunrise Cranes are cranes located in the Woods of the Lost and near Camp Nooka Nooka in the Jade Forest.",
	"Wandering Greenbacks are cranes located in Dawn's Blossom and the Shrine of the Dawn in the Jade Forest.",
	"Whitefeather Cranes can be found in the Singing Pools on the Wandering Isle. They are normally neutral, but will attack players with the Curses of the Frog and Turtle.",
	"Whitefisher Cranes are found in the Singing Marshes in Valley of the Four Winds and Deepwild in Krasarang Wilds.",
	"Windfeather Chicks are cranes located on the Timeless Isle.",
	"Windfeather Nestkeepers are cranes found in the immediate areas surrounding the Celestial Court in Timeless Isle.",
	"Brilliant Windfeathers are cranes located on the Timeless Isle.",
	"Fishgorged Cranes are found on the southern shore of Timeless Isle, between Old Pi'jiu and Firewalker Ruins.",
	"Fishgorged Cranes are one of a handful of non-rares on the isle that are not an objective of the  [Killing Time] achievement.",
	"Crane mounts can be bought from Jaluu the Generous <The Golden Lotus Quartermaster>, provided that you are Exalted with the Golden Lotus.",
	"There are currently three crane mounts available:  [Reins of the Azure Riding Crane] (500g), [Reins of the Regal Riding Crane] (1500g) and [Reins of the Golden Riding Crane] (2500g), but there are skins in the game files for additional crane mounts.",
	"The [Azure Crane Chick] pet has a chance to be found in Crane Nests on the Timeless Isle.",
	"The [Chi-Chi, Hatchling of Chi-Ji] pet can be purchased from Master Li on the Timeless Isle at a cost of 3 Celestial Coins.",
	"The [Devoured Wader] pet drops from the Swelling Tear rares in Bastion.",
	"[Jade Crane Chick] can be purchased by pandaren players from Battle Pet Trainers at a cost of 50s.",
	"[Pearlwing Heron] pet is a reward/vendor item from a covenant's special feature (Ember Court, Queen's Conservatory etc.)",
	"Cranes are a family of waterfowl cunning pets and are tamable by hunters starting at level 5. They like to eat fish and bread.",
	"If observed long enough, cranes can be seen eating a fish.",
	"Crows are a species of black-feathered birds, found in several areas throughout Kalimdor. One breed of crow, called the storm crow, has a special bond with the night elven druids, who are able to take their form.",
	"Storm crows are a type of crows that Druids of the Talon transform into.",
	"Duskwing Crows are found on the Isle of Reckoning in Kun-Lai Summit.",
	"Fjord Crows are found in Howling Fjord. Amusingly, they use the Storm Crow model, and thus have elven ears.",
	"Crow critters can be found on Darkmoon Island.",
	"Cocky Crows can be found resting on the  [Pandaren Scarecrow].",
	"Gilnean Crows are found in Gilneas.",
	'Dread ravens are a species of giant birds native to the world of Draenor. They are the children of the "Raven God", Anzu, and have close ties to the arakkoa.',
	"The dread ravens mostly went extinct when Spires of Arak were destroyed when Draenor became Outland. Yikkan Izu, who was transported to Azeroth to serve as a Brawler's Guild gladiator, is one of the few remaining specimens.",
	"Bathed in the blood of demons, corrupted dread ravens are significantly more aggressive, and will often kill one another if kept in confinement.",
	"Anzu is a dread raven god deeply tied to the arakkoa and the history of the Spires of Arak.",
	"Ka'alu, the Raven Mother, is a dread raven demigod and the consort of Anzu left to watch over the dread ravens when he vanished into the shadows after being cursed by Sethe.",
	"Bleakclaw is a fel-corrupted dread raven located in Tanaan Jungle.",
	"Darkscreech is a dread raven flight master located at the Crow's Crook‎ in Spires of Arak.",
	"Darktalon is found at [49.6, 41.8] on the rise south of Teluuna Observatory in central Shadowmoon Valley.",
	"Darkwing is a baby dread raven located at Veil Terokk‎ in Spires of Arak. It is a pet of Vesharr.",
	'Deathtalon is a dread raven located at the Ruins of Kra\'nak in Tanaan Jungle. When it spawns, it will be marked on the world map and a zone-wide announcement will be broadcasted: "Shadow Lord Iskar yells: Behind the veil, all you find is death!"',
	"Duskclaw is a dread raven located at Akeeta's Hovel in the Spires of Arak.",
	"Nisha is Rexxar's dread raven companion found in Sulfur Basin and Breaker's Crown in Gorgrond and in Darktide Roost in Shadowmoon Valley.",
	"Oskiira the Vengeful is found just south of Talon Altar in Spires of Arak. Behind Oskiira lies a nest of broken eggs, around the nest lies the remains of a dread raven and three Sethekk Chosen.",
	"Raketalon is an dread raven located at the Ring of Trials in Nagrand. After his demise, Raketalon's spirit appears and is reunited with his offsprings.",
	"Yikkan Izu alongside Izu's Ravens are the final encounter at Rank 6 in the Brawler's Guild.",
	"Adolescent Dread Ravens are dread ravens located in the Spires of Arak.",
	"Darktalon Hatchlings are dread ravens located in Shadowmoon Valley.",
	"Darktalon Hatchlings are dread ravens located in Shadowmoon Valley.",
	"Dread Raven Hatchlings are dread ravens located in Skyreach.",
	"Lunarfall Chicks are dread ravens located in Lunarfall in Shadowmoon Valley.",
	"The Lunarfall Matriarch is found at Lunarfall before constructing the Alliance garrison. In her nest, look for the Lunarfall Egg, which contains 5-10x [Garrison Resources]. The egg can only be found while Lunarfall is not in the garrison phase.",
	"Lunarfall Ravens are dread ravens located in Moonflower Valley in Shadowmoon Valley.",
	"[Reins of the Raven Lord] has a chance to drop from Anzu in Sethekk Halls on Heroic difficulty.",
	"[Reins of the Dread Raven] is granted upon purchase of the Warlords of Draenor Collector's Edition.",
	"[Reins of the Corrupted Dreadwing] can be purchased from Dawn-Seeker Krisek <Order of the Awakened> in Tanaan Jungle at a cost of 150,000 Apexis Crystal upon reaching Friendly with Order of the Awakened.",
	"Dread ravens are tamable by hunters as part of the bird of prey family. The flightless, corrupted model is unique to only one tamable NPC: Blaithe, as Anzu cannot be tamed.",
	"A dread raven Spirit Healer can be found in a corner of Skettis in the Spires of Arak, surrounded by several kaliri spirits.",
	"Dread ravens use the same skeleton and animations as skyscreamers.",
	"Dread ravens were originally untamable by hunters due to their rarity and their ties to the arakkoa. They were made tamable in patch 8.3.0.",
}
