local _, bFacts = ...																									

bFacts.fact = {
        'Ravens are great at mimicking human speech and sounds',
        'Ostriches have the largest eyes of any land animal',
        'Cardinals like to cover themselves in ants',
        'Owls devour their prey whole',
        'Some ducks sleep with one eye open',
        'Kiwis are sometimes called "honorary mammals since their feathers that feel like hair, heavy bones filled with marrow, and nostrils on the tip of their nose!',
        'Most hummingbirds weigh less than a nickel',
        'In ancient Greece, pigeons delivered the results of the Olympic games',
        'Parrots can learn to say hundreds of words',
        'Swiftlet nests are a delicacy in China',
        'Bassian thrushes find food by farting',
        'Woodpeckers hoard acorns',
        'The unique black and white coloring of penguins works as camoflage',
        'Hoatzin chicks are born with claws on their wings',
        'Budgies catch each other\'s yawns',
        'There are more than 18,000 bird species in the world',
        'Birds are the only animals with feathers',
        'All female birds lay eggs',
        'Birds flock together to protect themselves',
        'Birds evolved from dinosaurs',
        'Some birds can mimic human speech',
        'The ostrich has the largest eyes of any land animal',
        'Some birds sleep with one eye open',
        'The wandering albatross can sleep while flying',
        'Penguins can jump as high as 9 feet! They do this by building up speed in the water and blasting out of the water',
        'Crows can recognize human faces',
        'The hummingbird can have a heartbeat that measures up to 1260 beats per minute when it\'s in full flight',
        'Most birds do not hunt for prey and so do not need teeth',
        'Birds that eat insects, like worms and ants, and small animals use their beaks to grab and swallow their meal.',
        'A pair of birds can take a longer time in courtship than the very act of copulation',
        'Bird species like kiwis, ostriches, ducks, swans, and geese do not have a cloaca but have a penis instead.',
        'Birds like crows and ravens love to play.',
        'Birds act as pollinators, transferring seeds and nutrients as they fly from one region to another.',
        'The chicken is the closest living relative to the Tyrannosaurus Rex.',
        'Many birds kept as pets, including doves, parakeets, and lovebirds, enjoy living in pairs for companionship.',
        'The smallest bird egg belongs to the hummingbird and is the size of a pea.  The largest bird egg, from which the ostrich hatches, is the size of a cantaloupe.',
        'A bird\'s eye takes up about 50 percent of its head; our eyes take up about 5 percent of our head. To be comparable to a bird\'s eyes, our eyes would have to be the size of baseballs.',
        'The penguin is the only bird that can swim, but not fly. It is also the only bird that walks upright.',
        'Owls turn their heads almost 360 degrees (a complete circle) but they cannot move their eyes.',
        'Chickens have over 200 distinct noises they make for communicating.',
        'When it comes to birds, the males tend to have the more glamorous feather shape, coloration, songs, and dances.  Female birds choose their mate based on how attractive they find them!',
        'It is estimated that one third of all bird owners turn on a radio for their pet when they leave the house.',
        'The first bird domesticated by humans was the goose.',
        'Kiwi birds are blind, so they hunt by smell.',
        'Some breeds of chickens can lay colored eggs. The Ameraucana and Araucana can lay green or blue eggs.',
        'The common phrase “eat like a bird” should mean something quite different!  Many birds eat twice their weight in food each day.  In fact, a bird requires more food in proportion to its size than a baby or a cat.',
        'A group of larks is called an exaltation, a group of chickens is called a peep, a group of geese is called a gaggle, a group of ravens is called a murder, and a group of owls is called a parliament.',
        'Chickens that lay brown eggs have red ear lobes. There is a genetic link between the two.',
        'Crows have the largest cerebral hemispheres (brains), relative to body size, of any avian family.',
        'Mockingbirds can imitate many sounds, from a squeaking door to a cat meowing.',
        'Parasitic jaegers gather food by stealing it directly from the mouths of other birds.',
        'The average man would have to eat around 285 pounds of meat per day to maintain your weight if you had the metabolism of a hummingbird.',
        'Bearded vultures are the only birds to dye their plumage on purpose.',
        'The bearded vulture\'s diet consists of 70 to 90% bone, and it is the only bird in the world whose diet is like this, according to the World Wildlife Federation.',
        'With a wingspan of up to 9.5 feet, seen from far away, California Condors are sometimes mistaken for small aircrafts',
        'The Sword-billed Hummingbird is the only bird with a bill longer than its body.',
        'Approximately 2/3 of all the bird species are found in tropical rain forests.',
        'The longest feathers ever seen were on a chicken in Japan. Its tail feathers measured 34.7 feet (10.59 m) long.',
        'A bird\'s lungs are much more complicated and efficient and take up more space than those of mammals, such as humans. A human\'s lungs compose about 1/20 of its body, but a bird\'s takes up 1/5.',
        'The Australian pelican has the longest bill of any bird in the world. It is nearly 2 feet (0.5 m) in length. The sword-billed hummingbird, with its 3.9-inch (10 cm) bill, is the only bird with a bill that\'s longer than its body.',
        'Owls cannot swivel their eyes. Instead they move their heads completely around to see straight behind them. They live on every continent except Antarctica. Soft fringes on their wings make their flight essentially silent.',
        'Famous birds in cartoons, comics, and films include Big Bird in Sesame Street, Buzz Buzzard in Woody Woodpecker, Disney\'s Darkwing Duck, Footloops cereal\'s Toucan Sam, Woodstock in the Peanuts comic strip, Woody Woodpecker, and Iago in Aladdin.',
        'In the continental U.S. alone, between 1.4 billion and 3.7 billion birds are killed by cats annually.',
        'The only bird with nostrils at the end of its beak is the kiwi. This placement helps it sniff for food, such as worms and insects on the ground. It often snorts to clear its nostrils.',
        'Unlike most birds that sing, a woodpecker will drum its beak against a tree. Other woodpeckers can identify which bird it is by the sound of the drumming.',
        'The most talkative bird in the world is the African gray parrot. One parrot could say over 800 words. Most species of parrots can learn only 50.',
        'Many birds, such as starlings, sing notes too high for humans to hear.',
        'The chicks of large bird species often take the longest to hatch. Emu chicks, for example, take 60 days to hatch. Small songbirds take just 2 weeks.',
        'A green woodpecker can eat as many as 2,000 ants per day.',
        'The Japanese crested ibis is one of the rarest birds in the world. Probably fewer than 50 crested ibises are alive today.',
        'The 1989 Exxon Valdez oil spill in Alaska polluted approximately 1,180 miles of coastline and killed up to 100,000 seabirds.',
        'The bird with the most feathers is the whistling swan, with up to 25,000 feathers. Hummingbirds, on the other hand, are so small that they have fewer than 1,000.',
        'Falconry was developed more than 4,000 years ago in eastern and central Asia. Birds were used because they could kill animals beyond the range of a hunter\'s weapon. Genghis Khan reportedly had 10,000 falconers.',
        'Coalminers often used canaries to detect poisonous levels of carbon monoxide gas. Miners knew that if the canary passed out, they were in danger, too. The phrase “Canary in a Coalmine” derives from this history.',
        'The marsh warbler can mimic more than 80 different birds. Other renowned mimics include mockingbirds and lyrebirds.',
        'A pelican\'s pouch-like beak can hold up to 2.5 gallons of water at a time. The beak will shrink to squeeze out the water before the pelican swallows its food.',
        'A vulture named the Lammergeyer will fly with bones high in the air and then drop them onto rocks. It will then eat the smashed bones, like a circus sword swallower.',
        'The bird that lays the smallest egg in the world is the bee hummingbird. Its egg is just under 0.5" x 0.25" and weighs a mere 0.02 oz',
        'Though it looks like a bird\'s knee is bending backwards, what is bending backward is actually its ankle. Below its ankle is an extended foot bone, leading to the toes. A bird\'s real knee is usually hidden by feathers.',
        'The Malleefowl is famed for making a huge compost pile for its nest. Its eggs are incubated by the heat given off by the rotting vegetation.',
        'Social weaverbirds live in huge communal nests that look like a huge haystack spread across a treetop. Some nests can weigh a few tons, have over 400 birds living in them, and may be 100 years old.',
        'The heaviest bird of prey is the Andean condor. It can weigh up to 27 lb. (12 kg.)',
        'Many scientists believe that birds evolved from dinosaurs during the Mesozoic Era about 150 million years ago.',
        'Flamingos pair for a lifetime. Some stay with their mates for 50 years or more.',
        'In the United States alone, there are over 40 million pet birds.',
        'A bird\'s feathers weigh more than its skeleton.',
        'The type of diet a bird eats in the wild is directly related to the shape of a bird\'s beak.',
        'Approximately 75% of wild birds live for less than a year. The larger the bird, the more likely it is to live longer. The large wandering albatross, for example, can live for up to 80 years.',
        'Gentoo Penguins are the fastest swimming birds, reaching speeds of 22 mph (36 kph). Emperor Penguins can stay under water for up to 18 minutes.',
        'Arctic terns have the longest annual migration of any bird. They fly 25,000 miles (40,000 m) from the Arctic to the Antarctic and then back again.',
        'The bird with the greatest wingspan of any other bird is the Wandering Albatross at up to 11.8 ft (3.63 m).',
        'The largest, tallest, and heaviest bird in the world is the ostrich. Male ostriches can reach up to 9 ft. tall (2.7 m) and weigh up to 350 lb. (160 kg). Their eyes are bigger than any other land animals\' eyes and are even larger than their brain.',
        'The song of a European wren is made of more than 700 different notes a minute and can be heard 1,650 feet (500 m) away.',
        'The ostrich is the only bird that willingly takes care of other females\' eggs.',
        'Ostriches do not bury their heads in the sand when danger is near. But they have been seen to lie on the ground with their long neck stretched out flat if they want to hide.',
        'The Emperor Penguin is the only bird that lays its eggs in the middle of winter. By laying its eggs so early, it gives its young a head start. The babies need all spring, summer, and fall to grow big enough to survive the next winter.',
        'Oilbirds eat oil palm fruits, which make the birds oily too. People near the caves where the oilbirds lived used to trap the oilbirds and boil them down for the oil.',
        'The fastest flying bird in a dive is the Peregrine Falcon. It averages speeds of over 110 mph (180 kph).',
        'Oilbirds are the only birds that use echolocation the way that bats do. However, bats are much better at it. A bat can even fly through the blades of a moving fan. Oilbirds are also the only nocturnal fruit-eating birds in the world.',
        'Birds have three fingers on each wing. The first, the thumb, supports a small part of the wing called the alula (a.k.a bastard wing). The second and third fingers support the main flight feathers.',
        'Birds don\'t fall off of a branch when they sleep because their toes automatically clench around the twig they are standing on. Because the grabbing action is done by tendons rather than muscles, the birds can sleep without danger of falling.',
        'The wishbone (or “merrythought” bone) is a bird\'s fused collarbone. The strongest fliers have the widest angles in their wishbones. They are the only vertebrate animals to have a fused collarbone.',
        'Not all birds have equally hollow bones. Those that dive into water—like gannets, terns, and kingfishers—and those that fly very fast, like swifts, have less air in their long bones than other birds.',
        'The word "parakeet" literally means "long tail."',
        'An albatross can soar for as long as six hours without moving its wings.',
        'Birds typically have two, three, or four toes. A typical perching bird has three pointing forward, and one back. Birds that run on hard ground have only three, all pointing forward. Ostriches only have two toes, which are shaped like an antelope hoof.',
        'A Ruby-throated Hummingbird, which weighs less than 0.2 oz., has to beat its wings more than 52 times a second to hover in front of a flower.',
        'What keeps a bird up in the air is the shape of its wings. The first humans to discover how birds stay aloft were Australian Aborigines when they invented the boomerang.',
        'The fastest level flight by a bird has been seen in both the Spine-tailed Swift and the Red-breasted Merganser (a duck). They have flown at 100 mph (161 kph) in level flight.',
        'The slowest flying bird is the American Woodcock. It can fly at just 5 mph (8 kph). When hummingbirds hover, they move at 0 mph. Additionally, hummingbirds are the only birds that can fly backwards under power, registering a negative speed.',
        'The Rufous hummingbird is the smallest migrant bird. It is less than 4 in. (9 cm) long and flies every year from Alaska to Mexico, a round trip of 3,800 miles (6,400 km).',
        'Lighthouses are dangerous for birds. The beams attract birds, especially in misty conditions, and many are killed when they fly into the glass.',
        'Birds sense winter is coming by 1) changes in hormones that cause them to put on fat, 2) the changing length of the day, and 3) sensing small changes in air pressure, which is important in predicting weather changes.',
        'Crows can recognize and remember human faces, particularly faces they associate with bad experiences. They can even share their grudge against a specific person with other crows.',
        'A group of crows is called a murder or congress. A group of owls is called a parliament, wisdom, or study. A group of flamingos is called a flamboyance.',
        'The Bald Eagle builds the largest tree nest of all birds, measuring about 9.5 ft. (2.9 m) across. The largest nest ever found was nearly 10 ft. wide and weighed close to 3 tons.',
        'Woodcocks and many ducks have their eyes placed at the sides of their heads so that they have a 360-degree field of vision.',
        'A special arrangement of blood vessels cools the blood going out to the feet and warms the blood coming back, so even when standing on the ice, birds don\'t lose too much heat.',
        'Both the Bee and the Vervain Hummingbirds build the smallest nests of all birds, measuring 3/4" across and 1.2" deep.',
        'The most dangerous bird in the world is the Cassowary. With one kick it can kill its enemy.',
        'Birds that are raised for meat and eggs (poultry) are the largest source of protein eaten by humans.',
        'To attract a mate, a male Frigate bird will blow up its red throat pouch. The pouch can be as big as a person\'s head.',
        'Depending on the species, a woodpecker\'s tongue can be up to 4" long. It stores this long tongue by curling it in and sticking it through a specialized opening at the back of its neck, where it can then put it between the skull and skin.',
        'The seagulls in the Alfred Hitchcock movie The Birds (1963) were fed a mixture of wheat and whisky so they would stand around and not fly too much.',
        'The game Angry Birds has sold more than 7 million copies on Apple\'s iPhone. The game was made by a team of just four people. It was such a low priority for the company that it took over 8 months to finish.',
        'Wind farms kill approximately a half-million birds per year in the United States, according to a 2008 Fish and Wildlife study.',
        'Approximately 200 people have died since 1988 because of airborne collision between airplanes and birds.',
        'The first recorded bird strike was in 1905, when Orville Wright\'s plane hit a bird and killed it.',
        'In the novel To Kill a Mockingbird (1960), author Harper Lee used the mockingbird to symbolize innocence.',
        'The smallest flightless bird is the Island Rail. This tiny bird lives on the remote island of Tristan da Cunha in the Atlantic Ocean and is just 5" long, about the same size as a hen chick.',
        'The earliest known bird is the Archaeopteryx. It lived during the Jurassic period 150 million years ago. Because it did not have the basic features of flight, scientists are uncertain if it could fly',
        'Vultures have stomach acid so corrosive that they can digest carcasses infected with anthrax.',
        'No other living being other than birds have feathers. The main function is to help them fly. They also waterproof birds and protect them from UV rays and other harmful elements.',
        'Only one mammal can fly: the bat However, it flies differently from the bird. Insects also do not fly the same as birds.',
        'A Bald Eagle is called “bald” because it is piebald (black and white), not because it doesn\'t have any feathers.',
        'Eleven percent of the world\'s bird species is endangered. Draining wetlands and felling forests are the main causes of damage, but pollution and pesticides also play a part.',
        'Before 1840, there were thousands of millions of passenger pigeons in North America. However, they were slaughtered for food until only one was left, a female called Martha. She died when she was 12 years old in 1914, in a zoo in Ohio.',
        'The word "swan" is derived from the Indo-European root *swen, meaning "to sound, to sing."',
        'Someone who suffers from "anatidaephobia" believes that somewhere, somehow a duck or goose is constantly watching them.',
        'There are more fake flamingos on Earth than real ones.',
        'Though the term “eagle eyed” implies that eagles have keen vision, only the Wedge-tailed Eagle can see better than humans (2.5 times better). Kestrels and falcons have about the same power of sight as we do.',
        'The word "falcon" is from the Latin "falx," meaning "curved blade, pruning hook, sickle, war-scythe."',
        'A flock of ravens is called an “unkindness” or a "conspiracy."',
        'Esmeraldas Woodstar is one of the world\'s rarest and smallest hummingbirds, measuring barely 2½ inches long. It was thought to be extinct until it was rediscovered in 1990 after not being sighted since 1912.',
        'About two-thirds of birds in North America are at risk of extinction due to climate change.',
        'Unlike most animals, rather than producing liquid urine, birds create a white, pasty substance',
        'Ostriches are different than all the other bird species in that they do have a complete separation of feces and urine, but they still don\'t have a bladder like most mammals.',
        'A bird\'s lungs take up much more space in their bodies than a human\'s does. For example, a human\'s lungs makes up one twentieth of their body while a bird\'s take up one fifth',
        'Alabama\'s state bird is the Yellowhammer (also known as Northern Flicker)',
        'Alaska\'s state bird is the Willow Ptarmigan',
        'Arizona\'s state bird is the Cactus Wren',
        'Arkansas\'s state bird is the Mockingbird',
        'California\'s state bird is the California Quail',
        'Colorado\'s state bird is the Lark Bunting',
        'Connecticut\'s state bird is the American Robin',
        'Delaware\'s state bird is the Blue Hen Chicken',
        'Florida\'s state bird is the Mockingbird',
        'Georgia\'s state bird is the Brown Thrasher',
        'Hawaii\'s state bird is the Nene (Hawaiian Goose)',
        'Idaho\'s state bird is the Mountain Bluebird',
        'Illinois\'s state bird is the Cardinal',
        'Indiana\'s state bird is the Cardinal',
        'Iowa\'s state bird is the Eastern Goldfinch',
        'Kansas\'s state bird is the Western Meadowlark',
        'Kentucky\'s state bird is the Kentucky Warbler',
        'Louisiana\'s state bird is the Eastern Brown Pelican',
        'Maine\'s state bird is the Black-capped Chickadee',
        'Maryland\'s state bird is the Baltimore Oriole',
        'Massachusetts\'s state bird is the Black-capped Chickadee',
        'Michigan\'s state bird is the American Robin',
        'Minnesota\'s state bird is the Common Loon',
        'Mississippi\'s state bird is the Mockingbird',
        'Missouri\'s state bird is the Eastern Bluebird',
        'Montana\'s state bird is the Western Meadowlark',
        'Nebraska\'s state bird is the Western Meadowlark',
        'Nevada\'s state bird is the Mountain Bluebird',
        'New Hampshire\'s state bird is the Purple Finch',
        'New Jersey\'s state bird is the Eastern Goldfinch',
        'New Mexico\'s state bird is the Roadrunner',
        'New York\'s state bird is the Eastern Bluebird',
        'North Carolina\'s state bird is the Cardinal',
        'North Dakota\'s state bird is the Western Meadowlark',
        'Ohio\'s state bird is the Cardinal',
        'Oklahoma\'s state bird is the Scissor-tailed Flycatcher',
        'Oregon\'s state bird is the Western Meadowlark',
        'Pennsylvania\'s state bird is the Ruffed Grouse',
        'Rhode Island\'s state bird is the Rhode Island Red',
        'South Carolina\'s state bird is the Carolina Wren',
        'South Dakota\'s state bird is the Ring-necked Pheasant',
        'Tennessee\'s state bird is the Mockingbird',
        'Texas\'s state bird is the Mockingbird',
        'Utah\'s state bird is the California Gull',
        'Vermont\'s state bird is the Hermit Thrush',
        'Virginia\'s state bird is the Cardinal',
        'Washington\'s state bird is the Willow Goldfinch',
        'West Virginia\'s state bird is the Cardinal',
        'Wisconsin\'s state bird is the American Robin',
        'Wyoming\'s state bird is the Western Meadowlark',
        'Contrary to their portrayal in cartoons, roadrunners are not nearly as fast as coyotes. That said, they\'re pretty fast for birds. The land speed of a roadrunner is typically around 15 mph, though the bird can move faster in short bursts.',
        'There are 2 types of roadrunners: Greater (2ft, black/brown/white feathers, shaggy crest) & Lesser (smaller, lighter tan). Both have long tail feathers for balance.',
        'Roadrunners are omnivores that eat ground prey, including rattlesnakes. They primarily consume scorpions, frogs, reptiles, small mammals, birds, and eggs. If a pair wants to eat a rattlesnake, they work together to peck its head until it dies.',
        'Roadrunners are fast birds of the cuckoo family. The greater roadrunner\'s Latin name "Geococcyx californianus" means Californian earth-cuckoo.',
        'Roadrunners are charismatic birds, and being fleet of foot might just make them feel confident about exploring whatever they\'re curious about—including people.',
        'On cool desert nights, roadrunners allow their body temperature to drop to conserve their energy. To recover from their cold night, roadrunners spend the morning lying out in the sun, with their feathers raised to allow the sun to reach their skin.',
        'A group of geese is called a \'gaggle\'. However, when they are in they are they are a \'skein\'',
        'A group of vultures on the ground or perched in trees is called a \'venue.\' If they are circling on thermals of hot air, however, they are referred to as a "kettle".',
        'Many owl species are solitary, coming together only during breeding seasons. On the occasions when owls are seen together, the group is called a “parliament.”',
        'A group of peacocks is called an “ostentation.” Since ostentation means a pretentious or conspicuous show or display, it is easy to see why this name may fit the showy peacocks.',

}