local _, bFacts = ...

bFacts.fact = {
	"The hummingbird can have a heartbeat that measures up to 1260 beats per minute when it's in full flight",
	"Most birds do not hunt for prey and therefore do not need teeth",
	"Birds that eat insects, like worms and ants, and small animals use their beaks to grab and swallow their meal.",
	"A pair of birds can take a longer time in courtship than the very act of copulation",
	"Bird species like kiwis, ostriches, ducks, swans, and geese do not have a cloaca but have a penis instead.",
	"Birds like crows and ravens love to play.",
	"Birds act as pollinators, transferring seeds and nutrients as they fly from one region to another.",
	"The chicken is the closest living relative to the Tyrannosaurus Rex.",
	"Many birds kept as pets, including doves, parakeets, and lovebirds, enjoy living in pairs for companionship.",
	"The smallest bird egg belongs to the hummingbird and is the size of a pea.  The largest bird egg, from which the ostrich hatches, is the size of a cantaloupe.",
	"A bird's eye takes up about 50 percent of its head; our eyes take up about 5 percent of our head. To be comparable to a bird's eyes, our eyes would have to be the size of baseballs.",
	"The penguin is the only bird that can swim, but not fly. It is also the only bird that walks upright.",
	"Owls turn their heads almost 360 degrees (a complete circle) but they cannot move their eyes.",
	"Chickens have over 200 distinct noises they make for communicating.",
	"When it comes to birds, the males tend to have the more glamorous feather shape, coloration, songs, and dances.  Female birds choose their mate based on how attractive they find them!",
	"It is estimated that one third of all bird owners turn on a radio for their pet when they leave the house.",
	"The first bird domesticated by humans was the goose.",
	"Kiwi birds are blind, so they hunt by smell.",
	"Some breeds of chickens can lay colored eggs. The Ameraucana and Araucana can lay green or blue eggs.",
	"The common phrase “eat like a bird” should mean something quite different!  Many birds eat twice their weight in food each day.  In fact, a bird requires more food in proportion to its size than a baby or a cat.",
	"A group of larks is called an exaltation, a group of chickens is called a peep, a group of geese is called a gaggle, a group of ravens is called a murder, and a group of owls is called a parliament.",
	"Chickens that lay brown eggs have red ear lobes. There is a genetic link between the two.",
	"Crows have the largest cerebral hemispheres (brains), relative to body size, of any avian family.",
	"Mockingbirds can imitate many sounds, from a squeaking door to a cat meowing.",
	"Parasitic jaegers gather food by stealing it directly from the mouths of other birds.",
	"The average man would have to eat around 285 pounds of meat per day to maintain your weight if you had the metabolism of a hummingbird.",
	"Bearded vultures are the only birds to dye their plumage on purpose.",
	"The bearded vulture's diet consists of 70 to 90% bone, and it is the only bird in the world whose diet is like this, according to the World Wildlife Federation.",
	"With a wingspan of up to 9.5 feet, seen from far away, California Condors are sometimes mistaken for small aircrafts",
	"The Sword-billed Hummingbird is the only bird with a bill longer than its body.",
	"Approximately 2/3 of all the bird species are found in tropical rain forests.",
	"The longest feathers ever seen were on a chicken in Japan. Its tail feathers measured 34.7 feet (10.59 m) long.",
	"A bird's lungs are much more complicated and efficient and take up more space than those of mammals, such as humans. A human's lungs compose about 1/20 of its body, but a bird's takes up 1/5.",
	"The Australian pelican has the longest bill of any bird in the world. It is nearly 2 feet (0.5 m) in length. The sword-billed hummingbird, with its 3.9-inch (10 cm) bill, is the only bird with a bill that's longer than its body.",
	"Owls cannot swivel their eyes. Instead they move their heads completely around to see straight behind them. They live on every continent except Antarctica. Soft fringes on their wings make their flight essentially silent.",
	"In the continental U.S. alone, between 1.4 billion and 3.7 billion birds are killed by cats annually.",
	"The only bird with nostrils at the end of its beak is the kiwi. This placement helps it sniff for food, such as worms and insects on the ground. It often snorts to clear its nostrils.",
	"Unlike most birds that sing, a woodpecker will drum its beak against a tree. Other woodpeckers can identify which bird it is by the sound of the drumming.",
	"The most talkative bird in the world is the African gray parrot. One parrot could say over 800 words. Most species of parrots can learn only 50.",
	"Many birds, such as starlings, sing notes too high for humans to hear.",
	"The chicks of large bird species often take the longest to hatch. Emu chicks, for example, take 60 days to hatch. Small songbirds take just 2 weeks.",
	"A green woodpecker can eat as many as 2,000 ants per day.",
	"The Japanese crested ibis is one of the rarest birds in the world. Probably fewer than 50 crested ibises are alive today.",
	"The 1989 Exxon Valdez oil spill in Alaska polluted approximately 1,180 miles of coastline and killed up to 100,000 seabirds.",
	"The bird with the most feathers is the whistling swan, with up to 25,000 feathers. Hummingbirds, on the other hand, are so small that they have fewer than 1,000.",
	"Falconry was developed more than 4,000 years ago in eastern and central Asia. Birds were used because they could kill animals beyond the range of a hunter's weapon. Genghis Khan reportedly had 10,000 falconers.",
	"Coalminers often used canaries to detect poisonous levels of carbon monoxide gas. Miners knew that if the canary passed out, they were in danger, too. The phrase “Canary in a Coalmine” derives from this history.",
	"The marsh warbler can mimic more than 80 different birds. Other renowned mimics include mockingbirds and lyrebirds.",
	"A pelican's pouch-like beak can hold up to 2.5 gallons of water at a time. The beak will shrink to squeeze out the water before the pelican swallows its food.",
	"A vulture named the Lammergeyer will fly with bones high in the air and then drop them onto rocks. It will then eat the smashed bones, like a circus sword swallower.",
	'The bird that lays the smallest egg in the world is the bee hummingbird. Its egg is just under 0.5" x 0.25" and weighs a mere 0.02 oz',
	"Though it looks like a bird's knee is bending backwards, what is bending backward is actually its ankle. Below its ankle is an extended foot bone, leading to the toes. A bird's real knee is usually hidden by feathers.",
	"The Malleefowl is famed for making a huge compost pile for its nest. Its eggs are incubated by the heat given off by the rotting vegetation.",
	"Social weaverbirds live in huge communal nests that look like a huge haystack spread across a treetop. Some nests can weigh a few tons, have over 400 birds living in them, and may be 100 years old.",
	"The heaviest bird of prey is the Andean condor. It can weigh up to 27 lb. (12 kg.)",
	"Many scientists believe that birds evolved from dinosaurs during the Mesozoic Era about 150 million years ago.",
	"Flamingos pair for a lifetime. Some stay with their mates for 50 years or more.",
	"In the United States alone, there are over 40 million pet birds.",
	"A bird's feathers weigh more than its skeleton.",
	"The type of diet a bird eats in the wild is directly related to the shape of a bird's beak.",
	"Approximately 75% of wild birds live for less than a year. The larger the bird, the more likely it is to live longer. The large wandering albatross, for example, can live for up to 80 years.",
	"Gentoo Penguins are the fastest swimming birds, reaching speeds of 22 mph (36 kph). Emperor Penguins can stay under water for up to 18 minutes.",
	"Arctic terns have the longest annual migration of any bird. They fly 25,000 miles (40,000 m) from the Arctic to the Antarctic and then back again.",
	"The bird with the greatest wingspan of any other bird is the Wandering Albatross at up to 11.8 ft (3.63 m).",
	"The largest, tallest, and heaviest bird in the world is the ostrich. Male ostriches can reach up to 9 ft. tall (2.7 m) and weigh up to 350 lb. (160 kg). Their eyes are bigger than any other land animals' eyes and are even larger than their brain.",
	"The song of a European wren is made of more than 700 different notes a minute and can be heard 1,650 feet (500 m) away.",
	"The ostrich is the only bird that willingly takes care of other females' eggs.",
	"Ostriches do not bury their heads in the sand when danger is near. But they have been seen to lie on the ground with their long neck stretched out flat if they want to hide.",
	"The Emperor Penguin is the only bird that lays its eggs in the middle of winter. By laying its eggs so early, it gives its young a head start. The babies need all spring, summer, and fall to grow big enough to survive the next winter.",
	"Oilbirds eat oil palm fruits, which make the birds oily too. People near the caves where the oilbirds lived used to trap the oilbirds and boil them down for the oil.",
	"The fastest flying bird in a dive is the Peregrine Falcon. It averages speeds of over 110 mph (180 kph).",
	"Oilbirds are the only birds that use echolocation the way that bats do. However, bats are much better at it. A bat can even fly through the blades of a moving fan. Oilbirds are also the only nocturnal fruit-eating birds in the world.",
	"Birds have three fingers on each wing. The first, the thumb, supports a small part of the wing called the alula (a.k.a bastard wing). The second and third fingers support the main flight feathers.",
	"Birds don't fall off of a branch when they sleep because their toes automatically clench around the twig they are standing on. Because the grabbing action is done by tendons rather than muscles, the birds can sleep without danger of falling.",
	"The wishbone (or “merrythought” bone) is a bird's fused collarbone. The strongest fliers have the widest angles in their wishbones. They are the only vertebrate animals to have a fused collarbone.",
	"Not all birds have equally hollow bones. Those that dive into water—like gannets, terns, and kingfishers—and those that fly very fast, like swifts, have less air in their long bones than other birds.",
	'The word "parakeet" literally means "long tail."',
	"An albatross can soar for as long as six hours without moving its wings.",
	"Birds typically have two, three, or four toes. A typical perching bird has three pointing forward, and one back. Birds that run on hard ground have only three, all pointing forward. Ostriches only have two toes, which are shaped like an antelope hoof.",
	"A Ruby-throated Hummingbird, which weighs less than 0.2 oz., has to beat its wings more than 52 times a second to hover in front of a flower.",
	"What keeps a bird up in the air is the shape of its wings. The first humans to discover how birds stay aloft were Australian Aborigines when they invented the boomerang.",
	"The fastest level flight by a bird has been seen in both the Spine-tailed Swift and the Red-breasted Merganser (a duck). They have flown at 100 mph (161 kph) in level flight.",
	"The slowest flying bird is the American Woodcock. It can fly at just 5 mph (8 kph). When hummingbirds hover, they move at 0 mph. Additionally, hummingbirds are the only birds that can fly backwards under power, registering a negative speed.",
	"The Rufous hummingbird is the smallest migrant bird. It is less than 4 in. (9 cm) long and flies every year from Alaska to Mexico, a round trip of 3,800 miles (6,400 km).",
	"Lighthouses are dangerous for birds. The beams attract birds, especially in misty conditions, and many are killed when they fly into the glass.",
	"Birds sense winter is coming by 1) changes in hormones that cause them to put on fat, 2) the changing length of the day, and 3) sensing small changes in air pressure, which is important in predicting weather changes.",
	"Crows can recognize and remember human faces, particularly faces they associate with bad experiences. They can even share their grudge against a specific person with other crows.",
	"A group of crows is called a murder or congress. A group of owls is called a parliament, wisdom, or study. A group of flamingos is called a flamboyance.",
	"The Bald Eagle builds the largest tree nest of all birds, measuring about 9.5 ft. (2.9 m) across. The largest nest ever found was nearly 10 ft. wide and weighed close to 3 tons.",
	"Woodcocks and many ducks have their eyes placed at the sides of their heads so that they have a 360-degree field of vision.",
	"A special arrangement of blood vessels cools the blood going out to the feet and warms the blood coming back, so even when standing on the ice, birds don't lose too much heat.",
	'Both the Bee and the Vervain Hummingbirds build the smallest nests of all birds, measuring 3/4" across and 1.2" deep.',
	"The most dangerous bird in the world is the Cassowary. With one kick it can kill its enemy.",
	"Birds that are raised for meat and eggs (poultry) are the largest source of protein eaten by humans.",
	"To attract a mate, a male Frigate bird will blow up its red throat pouch. The pouch can be as big as a person's head.",
	"Depending on the species, a woodpecker's tongue can be up to 4\" long. It stores this long tongue by curling it in and sticking it through a specialized opening at the back of its neck, where it can then put it between the skull and skin.",
	"The seagulls in the Alfred Hitchcock movie The Birds (1963) were fed a mixture of wheat and whisky so they would stand around and not fly too much.",
	"The game Angry Birds has sold more than 7 million copies on Apple's iPhone. The game was made by a team of just four people. It was such a low priority for the company that it took over 8 months to finish.",
	"Wind farms kill approximately a half-million birds per year in the United States, according to a 2008 Fish and Wildlife study.",
	"Approximately 200 people have died since 1988 because of airborne collision between airplanes and birds.",
	"The first recorded bird strike was in 1905, when Orville Wright's plane hit a bird and killed it.",
	"In the novel To Kill a Mockingbird (1960), author Harper Lee used the mockingbird to symbolize innocence.",
	'The smallest flightless bird is the Island Rail. This tiny bird lives on the remote island of Tristan da Cunha in the Atlantic Ocean and is just 5" long, about the same size as a hen chick.',
	"The earliest known bird is the Archaeopteryx. It lived during the Jurassic period 150 million years ago. Because it did not have the basic features of flight, scientists are uncertain if it could fly",
	"Vultures have stomach acid so corrosive that they can digest carcasses infected with anthrax.",
	"No other living being other than birds have feathers. The main function is to help them fly. They also waterproof birds and protect them from UV rays and other harmful elements.",
	"A Bald Eagle is called “bald” because it is piebald (black and white), not because it doesn't have any feathers.",
	"Eleven percent of the world's bird species is endangered. Draining wetlands and felling forests are the main causes of damage, but pollution and pesticides also play a part.",
	"Before 1840, there were thousands of millions of passenger pigeons in North America. However, they were slaughtered for food until only one was left, a female called Martha. She died when she was 12 years old in 1914, in a zoo in Ohio.",
	'The word "swan" is derived from the Indo-European root *swen, meaning "to sound, to sing."',
	'Someone who suffers from "anatidaephobia" believes that somewhere, somehow a duck or goose is constantly watching them.',
	"There are more fake flamingos on Earth than real ones.",
	"Though the term “eagle eyed” implies that eagles have keen vision, only the Wedge-tailed Eagle can see better than humans (2.5 times better). Kestrels and falcons have about the same power of sight as we do.",
	'The word "falcon" is from the Latin "falx," meaning "curved blade, pruning hook, sickle, war-scythe."',
	'A flock of ravens is called an “unkindness” or a "conspiracy."',
	"Esmeraldas Woodstar is one of the world's rarest and smallest hummingbirds, measuring barely 2½ inches long. It was thought to be extinct until it was rediscovered in 1990 after not being sighted since 1912.",
	"About two-thirds of birds in North America are at risk of extinction due to climate change.",
	"Unlike most animals, rather than producing liquid urine, birds create a white, pasty substance",
	"Ostriches are different than all the other bird species in that they do have a complete separation of feces and urine, but they still don't have a bladder like most mammals.",
	"A bird's lungs take up much more space in their bodies than a human's does. For example, a human's lungs makes up one twentieth of their body while a bird's take up one fifth",
	"Alabama's state bird is the Yellowhammer (also known as Northern Flicker)",
	--[['Alaska\'s state bird is the Willow Ptarmigan',
        'Arizona\'s state bird is the Cactus Wren',
        'Arkansas\'s state bird is the Mockingbird',
        'California\'s state bird is the California Quail',
        'Colorado\'s state bird is the Lark Bunting',
        'Connecticut\'s state bird is the American Robin',
        'Delaware\'s state bird is the Blue Hen Chicken',
        'Florida\'s state bird is the Mockingbird',
        'Georgia\'s state bird is the Brown Thrasher',
        'Hawaii\'s state bird is the Nene (Hawaiian Goose)',
        'Idaho\'s state bird is the Mountain Bluebird',
        'Illinois\'s state bird is the Cardinal',
        'Indiana\'s state bird is the Cardinal',
        'Iowa\'s state bird is the Eastern Goldfinch',
        'Kansas\'s state bird is the Western Meadowlark',
        'Kentucky\'s state bird is the Kentucky Warbler',
        'Louisiana\'s state bird is the Eastern Brown Pelican',
        'Maine\'s state bird is the Black-capped Chickadee',
        'Maryland\'s state bird is the Baltimore Oriole',
        'Massachusetts\'s state bird is the Black-capped Chickadee',
        'Michigan\'s state bird is the American Robin',
        'Minnesota\'s state bird is the Common Loon',
        'Mississippi\'s state bird is the Mockingbird',
        'Missouri\'s state bird is the Eastern Bluebird',
        'Montana\'s state bird is the Western Meadowlark',
        'Nebraska\'s state bird is the Western Meadowlark',
        'Nevada\'s state bird is the Mountain Bluebird',
        'New Hampshire\'s state bird is the Purple Finch',
        'New Jersey\'s state bird is the Eastern Goldfinch',
        'New Mexico\'s state bird is the Roadrunner',
        'New York\'s state bird is the Eastern Bluebird',
        'North Carolina\'s state bird is the Cardinal',
        'North Dakota\'s state bird is the Western Meadowlark',
        'Ohio\'s state bird is the Cardinal',
        'Oklahoma\'s state bird is the Scissor-tailed Flycatcher',
        'Oregon\'s state bird is the Western Meadowlark',
        'Pennsylvania\'s state bird is the Ruffed Grouse',
        'Rhode Island\'s state bird is the Rhode Island Red',
        'South Carolina\'s state bird is the Carolina Wren',
        'South Dakota\'s state bird is the Ring-necked Pheasant',
        'Tennessee\'s state bird is the Mockingbird',
        'Texas\'s state bird is the Mockingbird',
        'Utah\'s state bird is the California Gull',
        'Vermont\'s state bird is the Hermit Thrush',
        'Virginia\'s state bird is the Cardinal',
        'Washington\'s state bird is the Willow Goldfinch',
        'West Virginia\'s state bird is the Cardinal',
        'Wisconsin\'s state bird is the American Robin',
        'Wyoming\'s state bird is the Western Meadowlark',]]
	--
	"Contrary to their portrayal in cartoons, roadrunners are not nearly as fast as coyotes. That said, they're pretty fast for birds. The land speed of a roadrunner is typically around 15 mph, though the bird can move faster in short bursts.",
	"There are 2 types of roadrunners: Greater (2ft, black/brown/white feathers, shaggy crest) & Lesser (smaller, lighter tan). Both have long tail feathers for balance.",
	"Roadrunners are omnivores that eat ground prey, including rattlesnakes. They primarily consume scorpions, frogs, reptiles, small mammals, birds, and eggs. If a pair wants to eat a rattlesnake, they work together to peck its head until it dies.",
	'Roadrunners are fast birds of the cuckoo family. The greater roadrunner\'s Latin name "Geococcyx californianus" means Californian earth-cuckoo.',
	"Roadrunners are charismatic birds, and being fleet of foot might just make them feel confident about exploring whatever they're curious about—including people.",
	"On cool desert nights, roadrunners allow their body temperature to drop to conserve their energy. To recover from their cold night, roadrunners spend the morning lying out in the sun, with their feathers raised to allow the sun to reach their skin.",
	"A group of geese is called a 'gaggle'. However, when they are in the sky they are they are a 'skein'",
	"A group of vultures on the ground or perched in trees is called a 'venue.' If they are circling on thermals of hot air, however, they are referred to as a \"kettle\".",
	"Many owl species are solitary, coming together only during breeding seasons. On the occasions when owls are seen together, the group is called a “parliament.”",
	"A group of peacocks is called an “ostentation.” Since ostentation means a pretentious or conspicuous show or display, it is easy to see why this name may fit the showy peacocks.",
	"Birds of a feather flock together",
	"Sparrows put the stubs of cigarettes in the lining of their nests. The reason they do this is to deter mites",
	"The beak of the great tit cleverly changes shape (very slightly) over the year to help it adapt to changes in its food supply from insects to nuts and seeds.",
	"Starlings are superb mimics. They can copy the sounds of other birds, and even frogs!",
	"House martins migrate all the way to Africa in winter, and then fly back to Britain and set up home in exactly the same nest.",
	"Starlings come together at night to roost in enormous numbers. The largest roosts can contain a million birds!",
	"Swifts gather flying insects into huge food balls, which contain between 300 and 1,000 insects each. The birds then use them to feed their young.",
	"You can tell male and female starlings apart by the colour of the base of the bill - blue for males, pink for females.",
	"Back when milk was delivered in glass bottles in Britain, the Blue Tit bird used to pierce the foil lid and drink the cream. This largely stopped when semi-skimmed milk became popular.",
	"Robins are incredibly charitable birds, sometimes feeding the chicks of other species - they just can't resist helping a hungry baby bird!",
	"Collared Doves are not master nest-makers - sometimes their chicks fall through the flimsy branches.",
	"Blackbirds love to sunbathe! They sit on the ground and spread out their wings to catch the rays.",
	"Birds have an incredibly high body temperature of 40°C, which requires a lot of energy to maintain. Birds have to eat enough during the day to keep them alive overnight - if not, they die before dawn.",
	"Blue tit birds are so light, they weigh about the same as a pound coin.",
	"Great Spotted Woodpeckers make their distinctive knocking sound by striking a branch with their bills an incredible 40 times a second.",
	"Wrens spend cold winters huddling together in nests for warmth. An astonishing 63 wrens were once found huddled in one nest box.",
	"Swallows can cover enormous distances during daylight migration - up to 200 miles a day.",
	"The jay bird stashes away about 5000 acorns every season in different hiding places. It can remember all the locations, but often it doesn't need to eat all the acorns, leaving them to grow into oak trees.",
	"Robins love singing so much, they do it all year round. They are normally the first to start the dawn chorus, and the last ones to stop at night.",
	"During winter, blackbird couples split up, but as soon as breeding season arrives, the pair up again, often with the same partner as before. Aw!",
	"Coal tit birds often purposefully lost battles of superiority over food, so they can hide it for later. They build a winter store of peanuts and sunflower seeds.",
	"Dunnock birds have one main partner for life, but they also have many other mates on the side. Females are just as likely to have affairs as males.",
	"During late summer and autumn, birds moult. Blackbirds are very embarrassed by this, and hide themselves away until their new feathers grow, leading people to think that the birds have disappeared.",
	"British robins are not afraid of humans, often coming quite close when we're gardening in the hope that we'll turn over the soil and expose tasty grub for them. European robins are not so brave.",
	"The tit family of birds spend most of their lives looking for something to eat. The great tit spends around 75% of its time searching for food. For the blue tit, it's more like 80%, and for the coal tit it can be 90%!",
	"The tits, chickadees, and titmice constitute the Paridae, a large family of small passerine birds which occur mainly in the Northern Hemisphere and Africa. Most were formerly classified in the genus Parus. ",
	"To draw a predator away from its nest, a Killdeer bird will drag its wing across the ground, faking an injury. When their display leads the threat away from the nest, they will suddenly become flightworthy and take off",
	"Some male birds, such as male Northern Cardinals, are known to fight their own reflections in a window, vehicle mirror, or chrome hubcap. It is believe these males believe their reflection is a competing bird and attack it",
	"Some birds deliberately disturb an ant mound and allow the ants to crawl over them. They smash the ants to get their ant juices on their feathers. It's believed the ant juices help eliminate parasites in their feathers",
	"Vultures like to urinate and defecate on their legs in order to stay cool via evaporative cooling. This is called urohidrosis",
	"Flycatchers and other birds that mainly hunt bugs will hunt flying insects in a technique called hawking. They simply perch on a branch and quickly dart out to snap the bug out of the air.",
	"Some gulls will carry clams or oysters high above the group and drop them onto rocks to break open the shells",
	"Crows use twigs to fish insects out of cracks and crevices",
	"Most predatory birds have strong feet and long, sharp talons to grasp and kill prey. Shrikes are predatory songbirds that lack this equipment but are still successful at hunting small birds and rodents",
	"Loggerhead and Northern Shrikes are predatory birds but don't have sharp talons to hunt their prey. They use their hooked beaks to impale their prey on barbed wire and rip them into bite size pieces! That's metal!",
	"All birds preen their feathers with their bills to keep them in good condition. Some birds, like the Great Blue Herons, have a middle claw with a serrated edge that acts like a comb. This class is called a pectinate claw.",
	"Nearly all birds will, at times, draw one leg up into their belly feathers for warmth and remain standing on the other leg.",
	"The Frillback is a breed of pigeon developed over many years of selective breeding. Frillbacks, along with other varieties of domesticated pigeons, are all descendants from the rock pigeon (Columba livia)",
	"The Frillback pigeon is a common and very popular breed of the domesticated pigeons. It is known for the frill or curls on the wing shield feathers.",
	"The quality of a Frillback bird is based on a 100-point scale, with the head constituting 15 points, the color constituting 15 points, the body constituting 10 points, the curl constituting 50 points, and the muff constituting 10 points.",
	"The Frillback pigeon is an exhibition or show breed. It is good for ornamental purpose and also good for raising as pets as they have a calm temperament.",
	"In daylight, birds crash into windows because they see reflections of vegetation or see through the glass to potted plants or vegetation on the other side. At night, nocturnal migrants (most songbirds) crash because they fly into lighted windows.",
	"Female toucans typically have higher voices than males. They use their calls to rally other birds to good foraging sites and to differentiate themselves from other groups of toucans.",
	"Falcons devote themselves to one partner for their reproductive years. However, this doesn't mean they act like a married couple. Falcons only come together to mate, and otherwise spend their lives as solitary hunters.",
	"Great Horned Owls, like other owls, are clueless about building nests. They use other available structures to nest in, which include stick nests of hawks and crows, squirrel nests, and a variety of artificial nests put up by humans.",
	"Contrary to popular belief, most birds are NOT government drones. However, this topic is heavily debated.",
	"Some bird species, such as the Common Loon, almost always have their feet in the water. Sometimes they'll lift their legs out of the water, shake off excess water, and tuck it under their wing for warmth.",
	"Chicken-like birds, such as the Sage Grouse, perform some of the more elaborate courtship displays in the bird world. Males gather in an open area to dance and strut and sometimes fight for the admiring females.",
	"Some birds not only lay eggs in their own nests, but they also lay some in the nests of other females in their species. Wood Ducks and Common Goldeneyes will even lay some of their eggs in the nests of other species!",
	"The Osprey bird is a fish-eating raptor with special feet. They have small, spine tipped projections, called papillae, on the bottom of their feet that help them hold their slippery fish prey",
	"Red-headed Woodpeckers experience the highest g-forces of all woodpeckers. When pecking wood, they hit trees up to 20 times per second about 12,000 times for day. Their brains experience 1000g's of deceleration!",
	"Owls cannot twist their heads all the way around, as some people think. With 14 vertebrae in their necks, owls can turn their heads up to 280 degrees!",
	"Bird claws are well adapted for daily activities. Birds that climb tree trunks, for example, have claws that are more curved compared with those of non-climbing species.",
	"The thermoregulation system of birds is very different from that of mammals. In mammals, the digestion of food produces heat and keeps their temperature around 98°F. Birds, however, need to shiver their muscles to maintain 106°F.",
	"Birds have large deposits of white fat in their bodies, mostly concentrated in the chest. White fat fuels flight and provides birds with the energy they need to shiver their muscles to keep warm.",
	"The Eurasian swift can stay in the air for months before they get sexually mature. They drink water by flying close to the surface of lakes and sleep flying high up in circles with one eye open. They land when sexually mature to raise young.",
	"Some birds that migrate from Europe to west Africa fly over the Sahara in one go without stopping to drink or eat. Climate change makes the journey even harder as the Sahara is expanding.",
	"Some hummingbirds have heart rates from 400-1200 bpm, but during their resting cycle (called Torpor), their heart rates can dip as low as 40 bpm.",
	"During mating displays, some male hummingbirds can pull up to 9 Gs.",
	"Turkey vultures are thought to have the strongest sense of smell of any vulture. In fact, their sense of smell is so strong that they are used as an indicator by gas companies to find gas leaks.",
	"Birds were the first animal found to be capable of keeping a musical beat, even when the tempo changes. The second animal found to have this capability was the Sea Lion.",
	"Birds ears are slightly offset. This gives them stereoscopic hearing capabilities. When a songbird calls, the birds can hear each individual frequency and tril. They get data about the amplitude, frequency, duration, direction of the sound waves.",
	"Baby birds will babble and go through baby talk as they learn to sing. Their throat structure does not have vocal cords but instead their entire throat is a resonating trumpet-like tube called the syrinx.",
	"Turkey Vultures produce antibodies to make them immune from botulism so they can eat rotting food that would harm other animals if they ate it.",
	"Birds breathe continuously - both in and out at the same time, constantly. It’s how they can manage to fly long distances, delivering a steady stream of oxygen throughout their bodies without breaks.",
	"Nuthatches are the only UK bird that can climb headfirst down tree trunks.",
	"House Finches are a common bird in much of the United States nowadays. They were originally only a resident of the Desert Southwest and Mexico. In the 1940’s someone brought them illegally to the East Coast and the birds were ultimately released.",
	"Zebra finches can metabolise their body fat and convert it to water to stay hydrated. They also have a specific song that they sing to eggs during droughts that causes the young to incubate for longer and hatch smaller and leaner to survive.",
	"Cockatoos have a dominant and non dominant foot. Most black cockatoos are left foot dominant ie they perch on their right and eat with their left foot.",
	"Baby emus have adorable striped camouflage and an instinct to tumble and roll at random intervals to avoid aerial predators.",
	"A lot of large parrots (macaws, cockatoos, African greys, etc) can live between 50-60yrs on average! One of the oldest known birds(a blue and yellow macaw) is about 124 and named Charlie.",
	"When a Peregrine Falcon pulls out of a full stoop (dive; that could reach 240+ mph) it has been estimated that they withstand over 27 Gs.",
	"The Hooded Pitohui is one of several known poisonous birds.",
	"Humans have more in common with birds than we do with all other primates regarding communication, particularly how we learn to communicate by way of mimicking.",
	"The entire starling population in North America started from 100 birds released in 1890. This wasn’t the first time introduction was attempted but the first time the birds survived. The current population in North America is over 150 million.",
	"Birds have special blood circulatory systems that help keep their feet from freezing called Rete mirabile- 'wonderful net' in Latin. It cools blood going into the feet to minimize heat loss, then warms it back up as it returns to the heart.",
	"North America used to be home to 5 to 10 billion passenger pigeons, which at the time were the most numerous birds on earth. One estimate put the size of a single flock at 2 billion birds.",
	"Lots of waterfowl like loons and grebes cannot take off from dry ground or walk on solid land because their legs are structured for swift swimming and can’t support the amount of body weight without the added buoyancy of water.",
	"Most raptor birds leave the nest at their full adult size after only about 12 weeks and are then eventually chased off the territory by their parents, who view them as competition for food.",
	"You can get a rough estimate of how old a raptor bird is by their plumage (juvenile plumage will molt out at about one year of age) and their eye color. Light eyes = young bird.",
	"Ayam Cemani is a rare breed of chicken from Indonesia. They have a dominant gene that causes hyperpigmentation (fibromelanosis), making the chicken mostly black, including feathers, beak, and internal organs.",
	"Kakapo birds are herbivores with a diverse diet including seeds, fruits, pollen, and plant material. They have a unique digestive system that allows them to extract maximum nutrients from fibrous plants.",
	"Kakapo birds are nocturnal and solitary, spending their days hidden in vegetation. They are excellent climbers, using their strong legs and beaks to move through trees.",
	"Kakapos have an unusual breeding system called lek breeding. Males gather in specific areas and compete for female attention through elaborate displays and booming calls. This typically occurs every 2-4 years when rimu trees produce abundant fruit.",
	"Kakapos birds are endemic to New Zealand, historically found throughout the country's forests. Today, they are restricted to predator-free island sanctuaries, primarily Codfish Island (Whenua Hou) and Little Barrier Island (Hauturu-o-Toi).",
	"The Chinstrap Penguin is easily identifiable by its distinctive black band extending from ear to ear under its chin, resembling a helmet strap. Its back and flippers are black, contrasting sharply with its white underparts and face.",
	"Chinstrap Penguins primarily feed on krill, which accounts for about 95% of their diet. They also consume small fish and squid. These penguins are skilled divers, capable of reaching depths of 70 meters to forage for food.",
	"Chinstrap Penguins are highly social, often forming large colonies during breeding season. They are agile swimmers, using their flippers to 'fly' underwater at speeds up to 30 km/h (8.3 mph).",
	"Chinstrap Penguins are known for their loud, harsh calls. During the breeding season, they produce a variety of vocalisations, including a high-pitched, repetitive screech often described as an 'ecstatic display call'.",
	"Chinstrap Penguins inhabit the Antarctic Peninsula, South Shetland, South Orkney, and South Sandwich Islands. They prefer rocky, ice-free areas for nesting, often on steep slopes or cliffs near the shore.",
	"The Cinereous Vulture is a massive bird of prey characterised by its dark brown to black plumage, which gives it a sombre, monk-like appearance. Unlike other vultures, its head is covered in fine, dark feathers, and it has a distinctive hooked beak.",
}

bFacts.wow = {
	"The alkonost, the sirin, the caladrius, the roc and the phoenix are all five mythical birds from legend and folklore. Each were attributed their own magical qualities and roles by various human societies in history",
	"In Russian legends, the alkonost was a creature with the head of a woman and the body of a bird. It could sing the most enchanting songs. Those who heard its song let go of everything they had ever known, desiring nothing more.",
	"Before Christian influence, the alkonost was believed to live on the magical island of Buyan. Similar to a bird of paradise in appearance, it was considered to be a wind spirit, able to summon up storms.",
	"In Russian legends, sirins had the top half of a woman, an owl-like body and were often depicted wearing a crown or halo.  They were often associated with the alkonost, but believed to have their origins in Greek myths concerning sirens.",
	"In Roman mythology, the caladrius was a bird with snow-white plumage that lived in the house of the king.  According to tradition, it had the power to absorb disease from a sick person, then flies away, curing the sick person",
	"In the mythology of the East, Middle East and Arabic countries, the Roc was a legendary gargantuan bird of prey.",
	"The phoenix was a mythical bird similar to — but not the same as — the Firebird in Slavic folklore, and whose counterpart is found in many other parts of the world. According to some myths it lived in 500 year cycles.",
	"Galarian Zapdos is the only known Pokémon capable of learning the move Thunderous Kick.",
	"Pidgeotto, an evolved form of the Pidgey. It is armed with sharp claws and dives from the sky to capture its prey. Unlike the more gentle Pidgey, Pidgeotto can be dangerous. Approach with extreme caution.",
	"Despite his imposing stature, Big Bird has a childlike personality. He is intensely curious about the world around him, likes being included in activities, and values his friends.",
	"Big Bird is a six-year-old walking, talking yellow bird with long orange legs, standing 8 feet 2 inches (2.49 metres) tall, who resides in a nest at 123 1/2 Sesame Street.",
	"The sea lion was the first Guinness animal advertisement Gilroy drew, which led to others featuring bears, kangaroos, ostriches and pelicans. But the toucan, which first appeared in 1935, prevailed.",
	"Toucan Sam is one of the cereal world's longest-serving mascots, serving as the face (and nose) of Froot Loops since 1963",
	"If you look closely at Toucan Sam's beak, you'll notice that there are actually three stripes on it: pink, red, and yellow-orange. The reason for these colors is no accident: They were among the original colors of the cereal!",
	"Famous birds in cartoons, comics, and films include Big Bird in Sesame Street, Buzz Buzzard in Woody Woodpecker, Disney's Darkwing Duck, Frootloops cereal's Toucan Sam, Woodstock in the Peanuts comic strip, Woody Woodpecker, and Iago in Aladdin.",
}
